//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.25 at 03:34:08 AM GMT 
//


package com.tesco.ofs.order.representation;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="AddressID" type="{http://www.sterlingcommerce.com/documentation/types}Text-256" />
 *       &lt;attribute name="AddressLine1" type="{http://www.sterlingcommerce.com/documentation/types}Address" />
 *       &lt;attribute name="AddressLine2" type="{http://www.sterlingcommerce.com/documentation/types}Address" />
 *       &lt;attribute name="AddressLine3" type="{http://www.sterlingcommerce.com/documentation/types}Address" />
 *       &lt;attribute name="AddressLine4" type="{http://www.sterlingcommerce.com/documentation/types}Address" />
 *       &lt;attribute name="AddressLine5" type="{http://www.sterlingcommerce.com/documentation/types}Address" />
 *       &lt;attribute name="AddressLine6" type="{http://www.sterlingcommerce.com/documentation/types}Address" />
 *       &lt;attribute name="AlternateEmailID" type="{http://www.sterlingcommerce.com/documentation/types}EMailID" />
 *       &lt;attribute name="Beeper" type="{http://www.sterlingcommerce.com/documentation/types}PhoneNo" />
 *       &lt;attribute name="City" type="{http://www.sterlingcommerce.com/documentation/types}City" />
 *       &lt;attribute name="Company" type="{http://www.sterlingcommerce.com/documentation/types}Company" />
 *       &lt;attribute name="Country" type="{http://www.sterlingcommerce.com/documentation/types}Country" />
 *       &lt;attribute name="DayFaxNo" type="{http://www.sterlingcommerce.com/documentation/types}PhoneNo" />
 *       &lt;attribute name="DayPhone" type="{http://www.sterlingcommerce.com/documentation/types}PhoneNo" />
 *       &lt;attribute name="Department" type="{http://www.sterlingcommerce.com/documentation/types}Department" />
 *       &lt;attribute name="EMailID" type="{http://www.sterlingcommerce.com/documentation/types}EMailID" />
 *       &lt;attribute name="EveningFaxNo" type="{http://www.sterlingcommerce.com/documentation/types}PhoneNo" />
 *       &lt;attribute name="EveningPhone" type="{http://www.sterlingcommerce.com/documentation/types}PhoneNo" />
 *       &lt;attribute name="FirstName" type="{http://www.sterlingcommerce.com/documentation/types}PersonName" />
 *       &lt;attribute name="IsAddressVerified" type="{http://www.sterlingcommerce.com/documentation/types}Flag" />
 *       &lt;attribute name="IsCommercialAddress" type="{http://www.sterlingcommerce.com/documentation/types}Flag" />
 *       &lt;attribute name="JobTitle" type="{http://www.sterlingcommerce.com/documentation/types}Title-40" />
 *       &lt;attribute name="LastName" type="{http://www.sterlingcommerce.com/documentation/types}PersonName" />
 *       &lt;attribute name="Latitude">
 *         &lt;simpleType>
 *           &lt;union>
 *             &lt;simpleType>
 *               &lt;restriction base="{http://www.sterlingcommerce.com/documentation/types}DecimalWithNegative">
 *               &lt;/restriction>
 *             &lt;/simpleType>
 *             &lt;simpleType>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                 &lt;enumeration value=""/>
 *               &lt;/restriction>
 *             &lt;/simpleType>
 *           &lt;/union>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="Longitude">
 *         &lt;simpleType>
 *           &lt;union>
 *             &lt;simpleType>
 *               &lt;restriction base="{http://www.sterlingcommerce.com/documentation/types}DecimalWithNegative">
 *               &lt;/restriction>
 *             &lt;/simpleType>
 *             &lt;simpleType>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                 &lt;enumeration value=""/>
 *               &lt;/restriction>
 *             &lt;/simpleType>
 *           &lt;/union>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="MiddleName" type="{http://www.sterlingcommerce.com/documentation/types}MiddleName" />
 *       &lt;attribute name="MobilePhone" type="{http://www.sterlingcommerce.com/documentation/types}PhoneNo" />
 *       &lt;attribute name="OtherPhone" type="{http://www.sterlingcommerce.com/documentation/types}PhoneNo" />
 *       &lt;attribute name="PersonID" type="{http://www.sterlingcommerce.com/documentation/types}PersonId" />
 *       &lt;attribute name="PersonInfoKey" type="{http://www.sterlingcommerce.com/documentation/types}Key" />
 *       &lt;attribute name="State" type="{http://www.sterlingcommerce.com/documentation/types}State" />
 *       &lt;attribute name="Suffix" type="{http://www.sterlingcommerce.com/documentation/types}Suffix" />
 *       &lt;attribute name="TaxGeoCode" type="{http://www.sterlingcommerce.com/documentation/types}GeoCode" />
 *       &lt;attribute name="Title" type="{http://www.sterlingcommerce.com/documentation/types}Title-10" />
 *       &lt;attribute name="ZipCode" type="{http://www.sterlingcommerce.com/documentation/types}ZipCode" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "BuyerContactAddress")
public class BuyerContactAddress {

    @XmlAttribute(name = "AddressID")
    protected String addressID;
    @XmlAttribute(name = "AddressLine1")
    protected String addressLine1;
    @XmlAttribute(name = "AddressLine2")
    protected String addressLine2;
    @XmlAttribute(name = "AddressLine3")
    protected String addressLine3;
    @XmlAttribute(name = "AddressLine4")
    protected String addressLine4;
    @XmlAttribute(name = "AddressLine5")
    protected String addressLine5;
    @XmlAttribute(name = "AddressLine6")
    protected String addressLine6;
    @XmlAttribute(name = "AlternateEmailID")
    protected String alternateEmailID;
    @XmlAttribute(name = "Beeper")
    protected String beeper;
    @XmlAttribute(name = "City")
    protected String city;
    @XmlAttribute(name = "Company")
    protected String company;
    @XmlAttribute(name = "Country")
    protected String country;
    @XmlAttribute(name = "DayFaxNo")
    protected String dayFaxNo;
    @XmlAttribute(name = "DayPhone")
    protected String dayPhone;
    @XmlAttribute(name = "Department")
    protected String department;
    @XmlAttribute(name = "EMailID")
    protected String eMailID;
    @XmlAttribute(name = "EveningFaxNo")
    protected String eveningFaxNo;
    @XmlAttribute(name = "EveningPhone")
    protected String eveningPhone;
    @XmlAttribute(name = "FirstName")
    protected String firstName;
    @XmlAttribute(name = "IsAddressVerified")
    protected String isAddressVerified;
    @XmlAttribute(name = "IsCommercialAddress")
    protected String isCommercialAddress;
    @XmlAttribute(name = "JobTitle")
    protected String jobTitle;
    @XmlAttribute(name = "LastName")
    protected String lastName;
    @XmlAttribute(name = "Latitude")
    protected String latitude;
    @XmlAttribute(name = "Longitude")
    protected String longitude;
    @XmlAttribute(name = "MiddleName")
    protected String middleName;
    @XmlAttribute(name = "MobilePhone")
    protected String mobilePhone;
    @XmlAttribute(name = "OtherPhone")
    protected String otherPhone;
    @XmlAttribute(name = "PersonID")
    protected String personID;
    @XmlAttribute(name = "PersonInfoKey")
    protected String personInfoKey;
    @XmlAttribute(name = "State")
    protected String state;
    @XmlAttribute(name = "Suffix")
    protected String suffix;
    @XmlAttribute(name = "TaxGeoCode")
    protected String taxGeoCode;
    @XmlAttribute(name = "Title")
    protected String title;
    @XmlAttribute(name = "ZipCode")
    protected String zipCode;

    /**
     * Gets the value of the addressID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressID() {
        return addressID;
    }

    /**
     * Sets the value of the addressID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressID(String value) {
        this.addressID = value;
    }

    /**
     * Gets the value of the addressLine1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressLine1() {
        return addressLine1;
    }

    /**
     * Sets the value of the addressLine1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressLine1(String value) {
        this.addressLine1 = value;
    }

    /**
     * Gets the value of the addressLine2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressLine2() {
        return addressLine2;
    }

    /**
     * Sets the value of the addressLine2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressLine2(String value) {
        this.addressLine2 = value;
    }

    /**
     * Gets the value of the addressLine3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressLine3() {
        return addressLine3;
    }

    /**
     * Sets the value of the addressLine3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressLine3(String value) {
        this.addressLine3 = value;
    }

    /**
     * Gets the value of the addressLine4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressLine4() {
        return addressLine4;
    }

    /**
     * Sets the value of the addressLine4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressLine4(String value) {
        this.addressLine4 = value;
    }

    /**
     * Gets the value of the addressLine5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressLine5() {
        return addressLine5;
    }

    /**
     * Sets the value of the addressLine5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressLine5(String value) {
        this.addressLine5 = value;
    }

    /**
     * Gets the value of the addressLine6 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressLine6() {
        return addressLine6;
    }

    /**
     * Sets the value of the addressLine6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressLine6(String value) {
        this.addressLine6 = value;
    }

    /**
     * Gets the value of the alternateEmailID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlternateEmailID() {
        return alternateEmailID;
    }

    /**
     * Sets the value of the alternateEmailID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlternateEmailID(String value) {
        this.alternateEmailID = value;
    }

    /**
     * Gets the value of the beeper property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBeeper() {
        return beeper;
    }

    /**
     * Sets the value of the beeper property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBeeper(String value) {
        this.beeper = value;
    }

    /**
     * Gets the value of the city property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCity() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCity(String value) {
        this.city = value;
    }

    /**
     * Gets the value of the company property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompany() {
        return company;
    }

    /**
     * Sets the value of the company property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompany(String value) {
        this.company = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountry(String value) {
        this.country = value;
    }

    /**
     * Gets the value of the dayFaxNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDayFaxNo() {
        return dayFaxNo;
    }

    /**
     * Sets the value of the dayFaxNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDayFaxNo(String value) {
        this.dayFaxNo = value;
    }

    /**
     * Gets the value of the dayPhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDayPhone() {
        return dayPhone;
    }

    /**
     * Sets the value of the dayPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDayPhone(String value) {
        this.dayPhone = value;
    }

    /**
     * Gets the value of the department property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepartment() {
        return department;
    }

    /**
     * Sets the value of the department property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepartment(String value) {
        this.department = value;
    }

    /**
     * Gets the value of the eMailID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEMailID() {
        return eMailID;
    }

    /**
     * Sets the value of the eMailID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEMailID(String value) {
        this.eMailID = value;
    }

    /**
     * Gets the value of the eveningFaxNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEveningFaxNo() {
        return eveningFaxNo;
    }

    /**
     * Sets the value of the eveningFaxNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEveningFaxNo(String value) {
        this.eveningFaxNo = value;
    }

    /**
     * Gets the value of the eveningPhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEveningPhone() {
        return eveningPhone;
    }

    /**
     * Sets the value of the eveningPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEveningPhone(String value) {
        this.eveningPhone = value;
    }

    /**
     * Gets the value of the firstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets the value of the firstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstName(String value) {
        this.firstName = value;
    }

    /**
     * Gets the value of the isAddressVerified property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsAddressVerified() {
        return isAddressVerified;
    }

    /**
     * Sets the value of the isAddressVerified property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsAddressVerified(String value) {
        this.isAddressVerified = value;
    }

    /**
     * Gets the value of the isCommercialAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsCommercialAddress() {
        return isCommercialAddress;
    }

    /**
     * Sets the value of the isCommercialAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsCommercialAddress(String value) {
        this.isCommercialAddress = value;
    }

    /**
     * Gets the value of the jobTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJobTitle() {
        return jobTitle;
    }

    /**
     * Sets the value of the jobTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJobTitle(String value) {
        this.jobTitle = value;
    }

    /**
     * Gets the value of the lastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets the value of the lastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastName(String value) {
        this.lastName = value;
    }

    /**
     * Gets the value of the latitude property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLatitude() {
        return latitude;
    }

    /**
     * Sets the value of the latitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLatitude(String value) {
        this.latitude = value;
    }

    /**
     * Gets the value of the longitude property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLongitude() {
        return longitude;
    }

    /**
     * Sets the value of the longitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLongitude(String value) {
        this.longitude = value;
    }

    /**
     * Gets the value of the middleName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMiddleName() {
        return middleName;
    }

    /**
     * Sets the value of the middleName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMiddleName(String value) {
        this.middleName = value;
    }

    /**
     * Gets the value of the mobilePhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMobilePhone() {
        return mobilePhone;
    }

    /**
     * Sets the value of the mobilePhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMobilePhone(String value) {
        this.mobilePhone = value;
    }

    /**
     * Gets the value of the otherPhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtherPhone() {
        return otherPhone;
    }

    /**
     * Sets the value of the otherPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtherPhone(String value) {
        this.otherPhone = value;
    }

    /**
     * Gets the value of the personID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPersonID() {
        return personID;
    }

    /**
     * Sets the value of the personID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersonID(String value) {
        this.personID = value;
    }

    /**
     * Gets the value of the personInfoKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPersonInfoKey() {
        return personInfoKey;
    }

    /**
     * Sets the value of the personInfoKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersonInfoKey(String value) {
        this.personInfoKey = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setState(String value) {
        this.state = value;
    }

    /**
     * Gets the value of the suffix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSuffix() {
        return suffix;
    }

    /**
     * Sets the value of the suffix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSuffix(String value) {
        this.suffix = value;
    }

    /**
     * Gets the value of the taxGeoCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxGeoCode() {
        return taxGeoCode;
    }

    /**
     * Sets the value of the taxGeoCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxGeoCode(String value) {
        this.taxGeoCode = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the zipCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZipCode() {
        return zipCode;
    }

    /**
     * Sets the value of the zipCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZipCode(String value) {
        this.zipCode = value;
    }

}
