//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.25 at 03:34:08 AM GMT 
//


package com.tesco.ofs.order.representation;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="BatchNo" type="{http://www.sterlingcommerce.com/documentation/types}Text-40" />
 *       &lt;attribute name="LotAttribute1" type="{http://www.sterlingcommerce.com/documentation/types}Text-40" />
 *       &lt;attribute name="LotAttribute2" type="{http://www.sterlingcommerce.com/documentation/types}Text-40" />
 *       &lt;attribute name="LotAttribute3" type="{http://www.sterlingcommerce.com/documentation/types}Text-40" />
 *       &lt;attribute name="LotKeyReference" type="{http://www.sterlingcommerce.com/documentation/types}Text-4000" />
 *       &lt;attribute name="LotNumber" type="{http://www.sterlingcommerce.com/documentation/types}Text-40" />
 *       &lt;attribute name="ManufacturingDate">
 *         &lt;simpleType>
 *           &lt;union>
 *             &lt;simpleType>
 *               &lt;restriction base="{http://www.sterlingcommerce.com/documentation/types}Date">
 *               &lt;/restriction>
 *             &lt;/simpleType>
 *             &lt;simpleType>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                 &lt;enumeration value=""/>
 *               &lt;/restriction>
 *             &lt;/simpleType>
 *           &lt;/union>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="RevisionNo" type="{http://www.sterlingcommerce.com/documentation/types}Text-40" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "OrderLineInvAttRequest")
public class OrderLineInvAttRequest {

    @XmlAttribute(name = "BatchNo")
    protected String batchNo;
    @XmlAttribute(name = "LotAttribute1")
    protected String lotAttribute1;
    @XmlAttribute(name = "LotAttribute2")
    protected String lotAttribute2;
    @XmlAttribute(name = "LotAttribute3")
    protected String lotAttribute3;
    @XmlAttribute(name = "LotKeyReference")
    protected String lotKeyReference;
    @XmlAttribute(name = "LotNumber")
    protected String lotNumber;
    @XmlAttribute(name = "ManufacturingDate")
    protected String manufacturingDate;
    @XmlAttribute(name = "RevisionNo")
    protected String revisionNo;

    /**
     * Gets the value of the batchNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBatchNo() {
        return batchNo;
    }

    /**
     * Sets the value of the batchNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBatchNo(String value) {
        this.batchNo = value;
    }

    /**
     * Gets the value of the lotAttribute1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLotAttribute1() {
        return lotAttribute1;
    }

    /**
     * Sets the value of the lotAttribute1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLotAttribute1(String value) {
        this.lotAttribute1 = value;
    }

    /**
     * Gets the value of the lotAttribute2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLotAttribute2() {
        return lotAttribute2;
    }

    /**
     * Sets the value of the lotAttribute2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLotAttribute2(String value) {
        this.lotAttribute2 = value;
    }

    /**
     * Gets the value of the lotAttribute3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLotAttribute3() {
        return lotAttribute3;
    }

    /**
     * Sets the value of the lotAttribute3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLotAttribute3(String value) {
        this.lotAttribute3 = value;
    }

    /**
     * Gets the value of the lotKeyReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLotKeyReference() {
        return lotKeyReference;
    }

    /**
     * Sets the value of the lotKeyReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLotKeyReference(String value) {
        this.lotKeyReference = value;
    }

    /**
     * Gets the value of the lotNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLotNumber() {
        return lotNumber;
    }

    /**
     * Sets the value of the lotNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLotNumber(String value) {
        this.lotNumber = value;
    }

    /**
     * Gets the value of the manufacturingDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getManufacturingDate() {
        return manufacturingDate;
    }

    /**
     * Sets the value of the manufacturingDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setManufacturingDate(String value) {
        this.manufacturingDate = value;
    }

    /**
     * Gets the value of the revisionNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRevisionNo() {
        return revisionNo;
    }

    /**
     * Sets the value of the revisionNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRevisionNo(String value) {
        this.revisionNo = value;
    }

}
