//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.25 at 03:34:08 AM GMT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.sterlingcommerce.com/documentation/YFS/createOrder/input", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.tesco.ofs.order.representation;
