//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.25 at 03:34:08 AM GMT 
//


package com.tesco.ofs.order.representation;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import com.fasterxml.jackson.annotation.JsonIgnore;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PaymentDetails" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="AuditTransactionId" type="{http://www.sterlingcommerce.com/documentation/types}TransactionID" />
 *                 &lt;attribute name="AuthAvs" type="{http://www.sterlingcommerce.com/documentation/types}Text-20" />
 *                 &lt;attribute name="AuthCode" type="{http://www.sterlingcommerce.com/documentation/types}Text-20" />
 *                 &lt;attribute name="AuthReturnCode" type="{http://www.sterlingcommerce.com/documentation/types}Text-20" />
 *                 &lt;attribute name="AuthReturnFlag" type="{http://www.sterlingcommerce.com/documentation/types}Text-20" />
 *                 &lt;attribute name="AuthReturnMessage" type="{http://www.sterlingcommerce.com/documentation/types}Text-255" />
 *                 &lt;attribute name="AuthTime" type="{http://www.sterlingcommerce.com/documentation/types}TimeStamp" />
 *                 &lt;attribute name="AuthorizationExpirationDate" type="{http://www.sterlingcommerce.com/documentation/types}TimeStamp" />
 *                 &lt;attribute name="AuthorizationID" type="{http://www.sterlingcommerce.com/documentation/types}Text-255" />
 *                 &lt;attribute name="CVVAuthCode" type="{http://www.sterlingcommerce.com/documentation/types}Text-20" />
 *                 &lt;attribute name="CallForAuthorizationStatus" type="{http://www.sterlingcommerce.com/documentation/types}CallForAuthStatus" />
 *                 &lt;attribute name="CashBackAmount">
 *                   &lt;simpleType>
 *                     &lt;union>
 *                       &lt;simpleType>
 *                         &lt;restriction base="{http://www.sterlingcommerce.com/documentation/types}PlusMinusMoney">
 *                         &lt;/restriction>
 *                       &lt;/simpleType>
 *                       &lt;simpleType>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                           &lt;enumeration value=""/>
 *                         &lt;/restriction>
 *                       &lt;/simpleType>
 *                     &lt;/union>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *                 &lt;attribute name="ChargeType" use="required" type="{http://www.sterlingcommerce.com/documentation/types}ChargeCategory" />
 *                 &lt;attribute name="CollectionDate" type="{http://www.sterlingcommerce.com/documentation/types}TimeStamp" />
 *                 &lt;attribute name="HoldAgainstBook" type="{http://www.sterlingcommerce.com/documentation/types}Flag" />
 *                 &lt;attribute name="InPerson" type="{http://www.sterlingcommerce.com/documentation/types}Flag" />
 *                 &lt;attribute name="InternalReturnCode" type="{http://www.sterlingcommerce.com/documentation/types}Text-20" />
 *                 &lt;attribute name="InternalReturnFlag" type="{http://www.sterlingcommerce.com/documentation/types}Text-20" />
 *                 &lt;attribute name="InternalReturnMessage" type="{http://www.sterlingcommerce.com/documentation/types}Text-255" />
 *                 &lt;attribute name="OfflineStatus" type="{http://www.sterlingcommerce.com/documentation/types}Flag" />
 *                 &lt;attribute name="PaymentEntryType" type="{http://www.sterlingcommerce.com/documentation/types}Text-100" />
 *                 &lt;attribute name="ProcessedAmount" type="{http://www.sterlingcommerce.com/documentation/types}ExternalAmount" />
 *                 &lt;attribute name="Reference1" type="{http://www.sterlingcommerce.com/documentation/types}Text-100" />
 *                 &lt;attribute name="Reference2" type="{http://www.sterlingcommerce.com/documentation/types}Text-100" />
 *                 &lt;attribute name="RequestAmount" type="{http://www.sterlingcommerce.com/documentation/types}ExternalAmount" />
 *                 &lt;attribute name="RequestId" type="{http://www.sterlingcommerce.com/documentation/types}Text-255" />
 *                 &lt;attribute name="RequestProcessed" type="{http://www.sterlingcommerce.com/documentation/types}Flag" />
 *                 &lt;attribute name="TranRequestTime" type="{http://www.sterlingcommerce.com/documentation/types}TimeStamp" />
 *                 &lt;attribute name="TranReturnCode" type="{http://www.sterlingcommerce.com/documentation/types}Text-20" />
 *                 &lt;attribute name="TranReturnFlag" type="{http://www.sterlingcommerce.com/documentation/types}Text-20" />
 *                 &lt;attribute name="TranReturnMessage" type="{http://www.sterlingcommerce.com/documentation/types}Text-255" />
 *                 &lt;attribute name="TranType" type="{http://www.sterlingcommerce.com/documentation/types}Text-40" />
 *                 &lt;attribute name="VoidTransaction" type="{http://www.sterlingcommerce.com/documentation/types}Flag" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "paymentDetails"
})
@XmlRootElement(name = "PaymentDetailsList")
public class PaymentDetailsList {

    @XmlElement(name = "PaymentDetails")
    protected List<PaymentDetailsList.PaymentDetails> paymentDetails;

    /**
     * Gets the value of the paymentDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the paymentDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPaymentDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PaymentDetailsList.PaymentDetails }
     * 
     * 
     */
    public List<PaymentDetailsList.PaymentDetails> getPaymentDetails() {
        if (paymentDetails == null) {
            paymentDetails = new ArrayList<PaymentDetailsList.PaymentDetails>();
        }
        return this.paymentDetails;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="AuditTransactionId" type="{http://www.sterlingcommerce.com/documentation/types}TransactionID" />
     *       &lt;attribute name="AuthAvs" type="{http://www.sterlingcommerce.com/documentation/types}Text-20" />
     *       &lt;attribute name="AuthCode" type="{http://www.sterlingcommerce.com/documentation/types}Text-20" />
     *       &lt;attribute name="AuthReturnCode" type="{http://www.sterlingcommerce.com/documentation/types}Text-20" />
     *       &lt;attribute name="AuthReturnFlag" type="{http://www.sterlingcommerce.com/documentation/types}Text-20" />
     *       &lt;attribute name="AuthReturnMessage" type="{http://www.sterlingcommerce.com/documentation/types}Text-255" />
     *       &lt;attribute name="AuthTime" type="{http://www.sterlingcommerce.com/documentation/types}TimeStamp" />
     *       &lt;attribute name="AuthorizationExpirationDate" type="{http://www.sterlingcommerce.com/documentation/types}TimeStamp" />
     *       &lt;attribute name="AuthorizationID" type="{http://www.sterlingcommerce.com/documentation/types}Text-255" />
     *       &lt;attribute name="CVVAuthCode" type="{http://www.sterlingcommerce.com/documentation/types}Text-20" />
     *       &lt;attribute name="CallForAuthorizationStatus" type="{http://www.sterlingcommerce.com/documentation/types}CallForAuthStatus" />
     *       &lt;attribute name="CashBackAmount">
     *         &lt;simpleType>
     *           &lt;union>
     *             &lt;simpleType>
     *               &lt;restriction base="{http://www.sterlingcommerce.com/documentation/types}PlusMinusMoney">
     *               &lt;/restriction>
     *             &lt;/simpleType>
     *             &lt;simpleType>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                 &lt;enumeration value=""/>
     *               &lt;/restriction>
     *             &lt;/simpleType>
     *           &lt;/union>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *       &lt;attribute name="ChargeType" use="required" type="{http://www.sterlingcommerce.com/documentation/types}ChargeCategory" />
     *       &lt;attribute name="CollectionDate" type="{http://www.sterlingcommerce.com/documentation/types}TimeStamp" />
     *       &lt;attribute name="HoldAgainstBook" type="{http://www.sterlingcommerce.com/documentation/types}Flag" />
     *       &lt;attribute name="InPerson" type="{http://www.sterlingcommerce.com/documentation/types}Flag" />
     *       &lt;attribute name="InternalReturnCode" type="{http://www.sterlingcommerce.com/documentation/types}Text-20" />
     *       &lt;attribute name="InternalReturnFlag" type="{http://www.sterlingcommerce.com/documentation/types}Text-20" />
     *       &lt;attribute name="InternalReturnMessage" type="{http://www.sterlingcommerce.com/documentation/types}Text-255" />
     *       &lt;attribute name="OfflineStatus" type="{http://www.sterlingcommerce.com/documentation/types}Flag" />
     *       &lt;attribute name="PaymentEntryType" type="{http://www.sterlingcommerce.com/documentation/types}Text-100" />
     *       &lt;attribute name="ProcessedAmount" type="{http://www.sterlingcommerce.com/documentation/types}ExternalAmount" />
     *       &lt;attribute name="Reference1" type="{http://www.sterlingcommerce.com/documentation/types}Text-100" />
     *       &lt;attribute name="Reference2" type="{http://www.sterlingcommerce.com/documentation/types}Text-100" />
     *       &lt;attribute name="RequestAmount" type="{http://www.sterlingcommerce.com/documentation/types}ExternalAmount" />
     *       &lt;attribute name="RequestId" type="{http://www.sterlingcommerce.com/documentation/types}Text-255" />
     *       &lt;attribute name="RequestProcessed" type="{http://www.sterlingcommerce.com/documentation/types}Flag" />
     *       &lt;attribute name="TranRequestTime" type="{http://www.sterlingcommerce.com/documentation/types}TimeStamp" />
     *       &lt;attribute name="TranReturnCode" type="{http://www.sterlingcommerce.com/documentation/types}Text-20" />
     *       &lt;attribute name="TranReturnFlag" type="{http://www.sterlingcommerce.com/documentation/types}Text-20" />
     *       &lt;attribute name="TranReturnMessage" type="{http://www.sterlingcommerce.com/documentation/types}Text-255" />
     *       &lt;attribute name="TranType" type="{http://www.sterlingcommerce.com/documentation/types}Text-40" />
     *       &lt;attribute name="VoidTransaction" type="{http://www.sterlingcommerce.com/documentation/types}Flag" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class PaymentDetails {

        @XmlAttribute(name = "AuditTransactionId")
        protected String auditTransactionId;
        @XmlAttribute(name = "AuthAvs")
        protected String authAvs;
        @XmlAttribute(name = "AuthCode")
        protected String authCode;
        @XmlAttribute(name = "AuthReturnCode")
        protected String authReturnCode;
        @XmlAttribute(name = "AuthReturnFlag")
        protected String authReturnFlag;
        @XmlAttribute(name = "AuthReturnMessage")
        protected String authReturnMessage;
        @XmlAttribute(name = "AuthTime")
        @JsonIgnore
        protected String authTime;
        @JsonIgnore
        @XmlAttribute(name = "AuthorizationExpirationDate")
        protected String authorizationExpirationDate;
        @XmlAttribute(name = "AuthorizationID")
        protected String authorizationID;
        @XmlAttribute(name = "CVVAuthCode")
        protected String cvvAuthCode;
        @XmlAttribute(name = "CallForAuthorizationStatus")
        protected String callForAuthorizationStatus;
        @XmlAttribute(name = "CashBackAmount")
        protected String cashBackAmount;
        @XmlAttribute(name = "ChargeType", required = true)
        protected String chargeType;
        @XmlAttribute(name = "CollectionDate")
        @JsonIgnore
        protected String collectionDate;
        @XmlAttribute(name = "HoldAgainstBook")
        protected String holdAgainstBook;
        @XmlAttribute(name = "InPerson")
        protected String inPerson;
        @XmlAttribute(name = "InternalReturnCode")
        protected String internalReturnCode;
        @XmlAttribute(name = "InternalReturnFlag")
        protected String internalReturnFlag;
        @XmlAttribute(name = "InternalReturnMessage")
        protected String internalReturnMessage;
        @XmlAttribute(name = "OfflineStatus")
        protected String offlineStatus;
        @XmlAttribute(name = "PaymentEntryType")
        protected String paymentEntryType;
        @XmlAttribute(name = "ProcessedAmount")
        protected BigDecimal processedAmount;
        @XmlAttribute(name = "Reference1")
        protected String reference1;
        @XmlAttribute(name = "Reference2")
        protected String reference2;
        @XmlAttribute(name = "RequestAmount")
        protected BigDecimal requestAmount;
        @XmlAttribute(name = "RequestId")
        protected String requestId;
        @XmlAttribute(name = "RequestProcessed")
        protected String requestProcessed;
        @XmlAttribute(name = "TranRequestTime")
        @JsonIgnore
        protected String tranRequestTime;
        @XmlAttribute(name = "TranReturnCode")
        protected String tranReturnCode;
        @XmlAttribute(name = "TranReturnFlag")
        protected String tranReturnFlag;
        @XmlAttribute(name = "TranReturnMessage")
        protected String tranReturnMessage;
        @XmlAttribute(name = "TranType")
        protected String tranType;
        @XmlAttribute(name = "VoidTransaction")
        protected String voidTransaction;

        /**
         * Gets the value of the auditTransactionId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAuditTransactionId() {
            return auditTransactionId;
        }

        /**
         * Sets the value of the auditTransactionId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAuditTransactionId(String value) {
            this.auditTransactionId = value;
        }

        /**
         * Gets the value of the authAvs property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAuthAvs() {
            return authAvs;
        }

        /**
         * Sets the value of the authAvs property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAuthAvs(String value) {
            this.authAvs = value;
        }

        /**
         * Gets the value of the authCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAuthCode() {
            return authCode;
        }

        /**
         * Sets the value of the authCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAuthCode(String value) {
            this.authCode = value;
        }

        /**
         * Gets the value of the authReturnCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAuthReturnCode() {
            return authReturnCode;
        }

        /**
         * Sets the value of the authReturnCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAuthReturnCode(String value) {
            this.authReturnCode = value;
        }

        /**
         * Gets the value of the authReturnFlag property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAuthReturnFlag() {
            return authReturnFlag;
        }

        /**
         * Sets the value of the authReturnFlag property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAuthReturnFlag(String value) {
            this.authReturnFlag = value;
        }

        /**
         * Gets the value of the authReturnMessage property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAuthReturnMessage() {
            return authReturnMessage;
        }

        /**
         * Sets the value of the authReturnMessage property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAuthReturnMessage(String value) {
            this.authReturnMessage = value;
        }

        /**
         * Gets the value of the authTime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAuthTime() {
            return authTime;
        }

        /**
         * Sets the value of the authTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAuthTime(String value) {
            this.authTime = value;
        }

        /**
         * Gets the value of the authorizationExpirationDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAuthorizationExpirationDate() {
            return authorizationExpirationDate;
        }

        /**
         * Sets the value of the authorizationExpirationDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAuthorizationExpirationDate(String value) {
            this.authorizationExpirationDate = value;
        }

        /**
         * Gets the value of the authorizationID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAuthorizationID() {
            return authorizationID;
        }

        /**
         * Sets the value of the authorizationID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAuthorizationID(String value) {
            this.authorizationID = value;
        }

        /**
         * Gets the value of the cvvAuthCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCVVAuthCode() {
            return cvvAuthCode;
        }

        /**
         * Sets the value of the cvvAuthCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCVVAuthCode(String value) {
            this.cvvAuthCode = value;
        }

        /**
         * Gets the value of the callForAuthorizationStatus property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCallForAuthorizationStatus() {
            return callForAuthorizationStatus;
        }

        /**
         * Sets the value of the callForAuthorizationStatus property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCallForAuthorizationStatus(String value) {
            this.callForAuthorizationStatus = value;
        }

        /**
         * Gets the value of the cashBackAmount property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCashBackAmount() {
            return cashBackAmount;
        }

        /**
         * Sets the value of the cashBackAmount property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCashBackAmount(String value) {
            this.cashBackAmount = value;
        }

        /**
         * Gets the value of the chargeType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getChargeType() {
            return chargeType;
        }

        /**
         * Sets the value of the chargeType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setChargeType(String value) {
            this.chargeType = value;
        }

        /**
         * Gets the value of the collectionDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCollectionDate() {
            return collectionDate;
        }

        /**
         * Sets the value of the collectionDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCollectionDate(String value) {
            this.collectionDate = value;
        }

        /**
         * Gets the value of the holdAgainstBook property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHoldAgainstBook() {
            return holdAgainstBook;
        }

        /**
         * Sets the value of the holdAgainstBook property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHoldAgainstBook(String value) {
            this.holdAgainstBook = value;
        }

        /**
         * Gets the value of the inPerson property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getInPerson() {
            return inPerson;
        }

        /**
         * Sets the value of the inPerson property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setInPerson(String value) {
            this.inPerson = value;
        }

        /**
         * Gets the value of the internalReturnCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getInternalReturnCode() {
            return internalReturnCode;
        }

        /**
         * Sets the value of the internalReturnCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setInternalReturnCode(String value) {
            this.internalReturnCode = value;
        }

        /**
         * Gets the value of the internalReturnFlag property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getInternalReturnFlag() {
            return internalReturnFlag;
        }

        /**
         * Sets the value of the internalReturnFlag property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setInternalReturnFlag(String value) {
            this.internalReturnFlag = value;
        }

        /**
         * Gets the value of the internalReturnMessage property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getInternalReturnMessage() {
            return internalReturnMessage;
        }

        /**
         * Sets the value of the internalReturnMessage property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setInternalReturnMessage(String value) {
            this.internalReturnMessage = value;
        }

        /**
         * Gets the value of the offlineStatus property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOfflineStatus() {
            return offlineStatus;
        }

        /**
         * Sets the value of the offlineStatus property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOfflineStatus(String value) {
            this.offlineStatus = value;
        }

        /**
         * Gets the value of the paymentEntryType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPaymentEntryType() {
            return paymentEntryType;
        }

        /**
         * Sets the value of the paymentEntryType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPaymentEntryType(String value) {
            this.paymentEntryType = value;
        }

        /**
         * Gets the value of the processedAmount property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getProcessedAmount() {
            return processedAmount;
        }

        /**
         * Sets the value of the processedAmount property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setProcessedAmount(BigDecimal value) {
            this.processedAmount = value;
        }

        /**
         * Gets the value of the reference1 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getReference1() {
            return reference1;
        }

        /**
         * Sets the value of the reference1 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setReference1(String value) {
            this.reference1 = value;
        }

        /**
         * Gets the value of the reference2 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getReference2() {
            return reference2;
        }

        /**
         * Sets the value of the reference2 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setReference2(String value) {
            this.reference2 = value;
        }

        /**
         * Gets the value of the requestAmount property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getRequestAmount() {
            return requestAmount;
        }

        /**
         * Sets the value of the requestAmount property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setRequestAmount(BigDecimal value) {
            this.requestAmount = value;
        }

        /**
         * Gets the value of the requestId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRequestId() {
            return requestId;
        }

        /**
         * Sets the value of the requestId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRequestId(String value) {
            this.requestId = value;
        }

        /**
         * Gets the value of the requestProcessed property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRequestProcessed() {
            return requestProcessed;
        }

        /**
         * Sets the value of the requestProcessed property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRequestProcessed(String value) {
            this.requestProcessed = value;
        }

        /**
         * Gets the value of the tranRequestTime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTranRequestTime() {
            return tranRequestTime;
        }

        /**
         * Sets the value of the tranRequestTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTranRequestTime(String value) {
            this.tranRequestTime = value;
        }

        /**
         * Gets the value of the tranReturnCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTranReturnCode() {
            return tranReturnCode;
        }

        /**
         * Sets the value of the tranReturnCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTranReturnCode(String value) {
            this.tranReturnCode = value;
        }

        /**
         * Gets the value of the tranReturnFlag property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTranReturnFlag() {
            return tranReturnFlag;
        }

        /**
         * Sets the value of the tranReturnFlag property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTranReturnFlag(String value) {
            this.tranReturnFlag = value;
        }

        /**
         * Gets the value of the tranReturnMessage property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTranReturnMessage() {
            return tranReturnMessage;
        }

        /**
         * Sets the value of the tranReturnMessage property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTranReturnMessage(String value) {
            this.tranReturnMessage = value;
        }

        /**
         * Gets the value of the tranType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTranType() {
            return tranType;
        }

        /**
         * Sets the value of the tranType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTranType(String value) {
            this.tranType = value;
        }

        /**
         * Gets the value of the voidTransaction property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVoidTransaction() {
            return voidTransaction;
        }

        /**
         * Sets the value of the voidTransaction property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVoidTransaction(String value) {
            this.voidTransaction = value;
        }

    }

}
