//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.25 at 03:34:08 AM GMT 
//


package com.tesco.ofs.order.representation;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OrderAuditDetail" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="IDs" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="ID" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="Name" type="{http://www.sterlingcommerce.com/documentation/types}Text-30" />
 *                                     &lt;attribute name="Value" type="{http://www.sterlingcommerce.com/documentation/types}Text-30" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Attributes" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Attribute" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="Extended">
 *                                       &lt;simpleType>
 *                                         &lt;restriction base="{http://www.sterlingcommerce.com/documentation/types}Flag">
 *                                           &lt;enumeration value="N"/>
 *                                           &lt;enumeration value="Y"/>
 *                                         &lt;/restriction>
 *                                       &lt;/simpleType>
 *                                     &lt;/attribute>
 *                                     &lt;attribute name="ModificationType" type="{http://www.sterlingcommerce.com/documentation/types}Text-40" />
 *                                     &lt;attribute name="Name" type="{http://www.sterlingcommerce.com/documentation/types}Text-30" />
 *                                     &lt;attribute name="NewValue" type="{http://www.sterlingcommerce.com/documentation/types}Text-100" />
 *                                     &lt;attribute name="OldValue" type="{http://www.sterlingcommerce.com/documentation/types}Text-100" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/all>
 *                 &lt;attribute name="Action" type="{http://www.sterlingcommerce.com/documentation/types}Text-10" />
 *                 &lt;attribute name="AuditType" type="{http://www.sterlingcommerce.com/documentation/types}Text-30" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "orderAuditDetail"
})
@XmlRootElement(name = "CustomAuditDetails")
public class CustomAuditDetails {

    @XmlElement(name = "OrderAuditDetail")
    protected List<CustomAuditDetails.OrderAuditDetail> orderAuditDetail;

    /**
     * Gets the value of the orderAuditDetail property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the orderAuditDetail property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrderAuditDetail().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CustomAuditDetails.OrderAuditDetail }
     * 
     * 
     */
    public List<CustomAuditDetails.OrderAuditDetail> getOrderAuditDetail() {
        if (orderAuditDetail == null) {
            orderAuditDetail = new ArrayList<CustomAuditDetails.OrderAuditDetail>();
        }
        return this.orderAuditDetail;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="IDs" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="ID" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="Name" type="{http://www.sterlingcommerce.com/documentation/types}Text-30" />
     *                           &lt;attribute name="Value" type="{http://www.sterlingcommerce.com/documentation/types}Text-30" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Attributes" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Attribute" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="Extended">
     *                             &lt;simpleType>
     *                               &lt;restriction base="{http://www.sterlingcommerce.com/documentation/types}Flag">
     *                                 &lt;enumeration value="N"/>
     *                                 &lt;enumeration value="Y"/>
     *                               &lt;/restriction>
     *                             &lt;/simpleType>
     *                           &lt;/attribute>
     *                           &lt;attribute name="ModificationType" type="{http://www.sterlingcommerce.com/documentation/types}Text-40" />
     *                           &lt;attribute name="Name" type="{http://www.sterlingcommerce.com/documentation/types}Text-30" />
     *                           &lt;attribute name="NewValue" type="{http://www.sterlingcommerce.com/documentation/types}Text-100" />
     *                           &lt;attribute name="OldValue" type="{http://www.sterlingcommerce.com/documentation/types}Text-100" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/all>
     *       &lt;attribute name="Action" type="{http://www.sterlingcommerce.com/documentation/types}Text-10" />
     *       &lt;attribute name="AuditType" type="{http://www.sterlingcommerce.com/documentation/types}Text-30" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class OrderAuditDetail {

        @XmlElement(name = "IDs")
        protected CustomAuditDetails.OrderAuditDetail.IDs iDs;
        @XmlElement(name = "Attributes")
        protected CustomAuditDetails.OrderAuditDetail.Attributes attributes;
        @XmlAttribute(name = "Action")
        protected String action;
        @XmlAttribute(name = "AuditType")
        protected String auditType;

        /**
         * Gets the value of the iDs property.
         * 
         * @return
         *     possible object is
         *     {@link CustomAuditDetails.OrderAuditDetail.IDs }
         *     
         */
        public CustomAuditDetails.OrderAuditDetail.IDs getIDs() {
            return iDs;
        }

        /**
         * Sets the value of the iDs property.
         * 
         * @param value
         *     allowed object is
         *     {@link CustomAuditDetails.OrderAuditDetail.IDs }
         *     
         */
        public void setIDs(CustomAuditDetails.OrderAuditDetail.IDs value) {
            this.iDs = value;
        }

        /**
         * Gets the value of the attributes property.
         * 
         * @return
         *     possible object is
         *     {@link CustomAuditDetails.OrderAuditDetail.Attributes }
         *     
         */
        public CustomAuditDetails.OrderAuditDetail.Attributes getAttributes() {
            return attributes;
        }

        /**
         * Sets the value of the attributes property.
         * 
         * @param value
         *     allowed object is
         *     {@link CustomAuditDetails.OrderAuditDetail.Attributes }
         *     
         */
        public void setAttributes(CustomAuditDetails.OrderAuditDetail.Attributes value) {
            this.attributes = value;
        }

        /**
         * Gets the value of the action property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAction() {
            return action;
        }

        /**
         * Sets the value of the action property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAction(String value) {
            this.action = value;
        }

        /**
         * Gets the value of the auditType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAuditType() {
            return auditType;
        }

        /**
         * Sets the value of the auditType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAuditType(String value) {
            this.auditType = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Attribute" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="Extended">
         *                   &lt;simpleType>
         *                     &lt;restriction base="{http://www.sterlingcommerce.com/documentation/types}Flag">
         *                       &lt;enumeration value="N"/>
         *                       &lt;enumeration value="Y"/>
         *                     &lt;/restriction>
         *                   &lt;/simpleType>
         *                 &lt;/attribute>
         *                 &lt;attribute name="ModificationType" type="{http://www.sterlingcommerce.com/documentation/types}Text-40" />
         *                 &lt;attribute name="Name" type="{http://www.sterlingcommerce.com/documentation/types}Text-30" />
         *                 &lt;attribute name="NewValue" type="{http://www.sterlingcommerce.com/documentation/types}Text-100" />
         *                 &lt;attribute name="OldValue" type="{http://www.sterlingcommerce.com/documentation/types}Text-100" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "attribute"
        })
        public static class Attributes {

            @XmlElement(name = "Attribute", required = true)
            protected List<CustomAuditDetails.OrderAuditDetail.Attributes.Attribute> attribute;

            /**
             * Gets the value of the attribute property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the attribute property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getAttribute().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link CustomAuditDetails.OrderAuditDetail.Attributes.Attribute }
             * 
             * 
             */
            public List<CustomAuditDetails.OrderAuditDetail.Attributes.Attribute> getAttribute() {
                if (attribute == null) {
                    attribute = new ArrayList<CustomAuditDetails.OrderAuditDetail.Attributes.Attribute>();
                }
                return this.attribute;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="Extended">
             *         &lt;simpleType>
             *           &lt;restriction base="{http://www.sterlingcommerce.com/documentation/types}Flag">
             *             &lt;enumeration value="N"/>
             *             &lt;enumeration value="Y"/>
             *           &lt;/restriction>
             *         &lt;/simpleType>
             *       &lt;/attribute>
             *       &lt;attribute name="ModificationType" type="{http://www.sterlingcommerce.com/documentation/types}Text-40" />
             *       &lt;attribute name="Name" type="{http://www.sterlingcommerce.com/documentation/types}Text-30" />
             *       &lt;attribute name="NewValue" type="{http://www.sterlingcommerce.com/documentation/types}Text-100" />
             *       &lt;attribute name="OldValue" type="{http://www.sterlingcommerce.com/documentation/types}Text-100" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Attribute {

                @XmlAttribute(name = "Extended")
                protected String extended;
                @XmlAttribute(name = "ModificationType")
                protected String modificationType;
                @XmlAttribute(name = "Name")
                protected String name;
                @XmlAttribute(name = "NewValue")
                protected String newValue;
                @XmlAttribute(name = "OldValue")
                protected String oldValue;

                /**
                 * Gets the value of the extended property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getExtended() {
                    return extended;
                }

                /**
                 * Sets the value of the extended property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setExtended(String value) {
                    this.extended = value;
                }

                /**
                 * Gets the value of the modificationType property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getModificationType() {
                    return modificationType;
                }

                /**
                 * Sets the value of the modificationType property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setModificationType(String value) {
                    this.modificationType = value;
                }

                /**
                 * Gets the value of the name property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getName() {
                    return name;
                }

                /**
                 * Sets the value of the name property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setName(String value) {
                    this.name = value;
                }

                /**
                 * Gets the value of the newValue property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getNewValue() {
                    return newValue;
                }

                /**
                 * Sets the value of the newValue property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setNewValue(String value) {
                    this.newValue = value;
                }

                /**
                 * Gets the value of the oldValue property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getOldValue() {
                    return oldValue;
                }

                /**
                 * Sets the value of the oldValue property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setOldValue(String value) {
                    this.oldValue = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="ID" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="Name" type="{http://www.sterlingcommerce.com/documentation/types}Text-30" />
         *                 &lt;attribute name="Value" type="{http://www.sterlingcommerce.com/documentation/types}Text-30" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "id"
        })
        public static class IDs {

            @XmlElement(name = "ID")
            protected List<CustomAuditDetails.OrderAuditDetail.IDs.ID> id;

            /**
             * Gets the value of the id property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the id property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getID().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link CustomAuditDetails.OrderAuditDetail.IDs.ID }
             * 
             * 
             */
            public List<CustomAuditDetails.OrderAuditDetail.IDs.ID> getID() {
                if (id == null) {
                    id = new ArrayList<CustomAuditDetails.OrderAuditDetail.IDs.ID>();
                }
                return this.id;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="Name" type="{http://www.sterlingcommerce.com/documentation/types}Text-30" />
             *       &lt;attribute name="Value" type="{http://www.sterlingcommerce.com/documentation/types}Text-30" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class ID {

                @XmlAttribute(name = "Name")
                protected String name;
                @XmlAttribute(name = "Value")
                protected String value;

                /**
                 * Gets the value of the name property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getName() {
                    return name;
                }

                /**
                 * Sets the value of the name property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setName(String value) {
                    this.name = value;
                }

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setValue(String value) {
                    this.value = value;
                }

            }

        }

    }

}
