//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.25 at 03:34:08 AM GMT 
//


package com.tesco.ofs.order.representation;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="FileAttachmentKey" type="{http://www.sterlingcommerce.com/documentation/types}Key" />
 *       &lt;attribute name="FileContentType" type="{http://www.sterlingcommerce.com/documentation/types}FileContentType" />
 *       &lt;attribute name="FileDescription" type="{http://www.sterlingcommerce.com/documentation/types}Description-255" />
 *       &lt;attribute name="FileLocation" type="{http://www.sterlingcommerce.com/documentation/types}FileLocation" />
 *       &lt;attribute name="FileName" type="{http://www.sterlingcommerce.com/documentation/types}FileName" />
 *       &lt;attribute name="FileSize">
 *         &lt;simpleType>
 *           &lt;union>
 *             &lt;simpleType>
 *               &lt;restriction base="{http://www.sterlingcommerce.com/documentation/types}FileSize">
 *               &lt;/restriction>
 *             &lt;/simpleType>
 *             &lt;simpleType>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                 &lt;enumeration value=""/>
 *               &lt;/restriction>
 *             &lt;/simpleType>
 *           &lt;/union>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="Operation" type="{http://www.sterlingcommerce.com/documentation/types}String" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "FileAttachment")
public class FileAttachment {

    @XmlAttribute(name = "FileAttachmentKey")
    protected String fileAttachmentKey;
    @XmlAttribute(name = "FileContentType")
    protected String fileContentType;
    @XmlAttribute(name = "FileDescription")
    protected String fileDescription;
    @XmlAttribute(name = "FileLocation")
    protected String fileLocation;
    @XmlAttribute(name = "FileName")
    protected String fileName;
    @XmlAttribute(name = "FileSize")
    protected String fileSize;
    @XmlAttribute(name = "Operation")
    protected String operation;

    /**
     * Gets the value of the fileAttachmentKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileAttachmentKey() {
        return fileAttachmentKey;
    }

    /**
     * Sets the value of the fileAttachmentKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileAttachmentKey(String value) {
        this.fileAttachmentKey = value;
    }

    /**
     * Gets the value of the fileContentType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileContentType() {
        return fileContentType;
    }

    /**
     * Sets the value of the fileContentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileContentType(String value) {
        this.fileContentType = value;
    }

    /**
     * Gets the value of the fileDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileDescription() {
        return fileDescription;
    }

    /**
     * Sets the value of the fileDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileDescription(String value) {
        this.fileDescription = value;
    }

    /**
     * Gets the value of the fileLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileLocation() {
        return fileLocation;
    }

    /**
     * Sets the value of the fileLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileLocation(String value) {
        this.fileLocation = value;
    }

    /**
     * Gets the value of the fileName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * Sets the value of the fileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileName(String value) {
        this.fileName = value;
    }

    /**
     * Gets the value of the fileSize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileSize() {
        return fileSize;
    }

    /**
     * Sets the value of the fileSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileSize(String value) {
        this.fileSize = value;
    }

    /**
     * Gets the value of the operation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperation() {
        return operation;
    }

    /**
     * Sets the value of the operation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperation(String value) {
        this.operation = value;
    }

}
