//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.25 at 03:34:08 AM GMT 
//


package com.tesco.ofs.order.representation;

import java.math.BigDecimal;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import com.fasterxml.jackson.annotation.JsonProperty;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="AlternateItemID" type="{http://www.sterlingcommerce.com/documentation/types}ItemID" />
 *       &lt;attribute name="BundleFulfillmentMode">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.sterlingcommerce.com/documentation/types}Text-2">
 *             &lt;enumeration value=""/>
 *             &lt;enumeration value="00"/>
 *             &lt;enumeration value="01"/>
 *             &lt;enumeration value="02"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="CostCurrency" type="{http://www.sterlingcommerce.com/documentation/types}Currency" />
 *       &lt;attribute name="CountryOfOrigin" type="{http://www.sterlingcommerce.com/documentation/types}Country" />
 *       &lt;attribute name="CustomerItem" type="{http://www.sterlingcommerce.com/documentation/types}Text-40" />
 *       &lt;attribute name="CustomerItemDesc" type="{http://www.sterlingcommerce.com/documentation/types}Text-500" />
 *       &lt;attribute name="ECCNNo" type="{http://www.sterlingcommerce.com/documentation/types}Text-40" />
 *       &lt;attribute name="HarmonizedCode" type="{http://www.sterlingcommerce.com/documentation/types}Text-40" />
 *       &lt;attribute name="ISBN" type="{http://www.sterlingcommerce.com/documentation/types}Text-40" />
 *       &lt;attribute name="ItemDesc" type="{http://www.sterlingcommerce.com/documentation/types}Text-500" />
 *       &lt;attribute name="ItemID" type="{http://www.sterlingcommerce.com/documentation/types}ItemID" />
 *       &lt;attribute name="ItemShortDesc" type="{http://www.sterlingcommerce.com/documentation/types}Text-200" />
 *       &lt;attribute name="ItemWeight" type="{http://www.sterlingcommerce.com/documentation/types}Dimension" />
 *       &lt;attribute name="ItemWeightUOM" type="{http://www.sterlingcommerce.com/documentation/types}UOM" />
 *       &lt;attribute name="ManufacturerItem" type="{http://www.sterlingcommerce.com/documentation/types}Text-100" />
 *       &lt;attribute name="ManufacturerItemDesc" type="{http://www.sterlingcommerce.com/documentation/types}Text-254" />
 *       &lt;attribute name="ManufacturerName" type="{http://www.sterlingcommerce.com/documentation/types}Text-50" />
 *       &lt;attribute name="NMFCClass" type="{http://www.sterlingcommerce.com/documentation/types}Text-100" />
 *       &lt;attribute name="NMFCCode" type="{http://www.sterlingcommerce.com/documentation/types}Text-40" />
 *       &lt;attribute name="NMFCDescription" type="{http://www.sterlingcommerce.com/documentation/types}Text-100" />
 *       &lt;attribute name="ProductClass" type="{http://www.sterlingcommerce.com/documentation/types}ProductClass" />
 *       &lt;attribute name="ProductLine" type="{http://www.sterlingcommerce.com/documentation/types}Text-100" />
 *       &lt;attribute name="ScheduleBCode" type="{http://www.sterlingcommerce.com/documentation/types}Text-40" />
 *       &lt;attribute name="SupplierItem" type="{http://www.sterlingcommerce.com/documentation/types}Text-40" />
 *       &lt;attribute name="SupplierItemDesc" type="{http://www.sterlingcommerce.com/documentation/types}ItemDesc" />
 *       &lt;attribute name="TaxProductCode" type="{http://www.sterlingcommerce.com/documentation/types}Text-40" />
 *       &lt;attribute name="UPCCode" type="{http://www.sterlingcommerce.com/documentation/types}Text-40" />
 *       &lt;attribute name="UnitCost" type="{http://www.sterlingcommerce.com/documentation/types}UnitPrice" />
 *       &lt;attribute name="UnitOfMeasure" type="{http://www.sterlingcommerce.com/documentation/types}UOM" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "Item")
public class Item {

    @XmlAttribute(name = "AlternateItemID")
    protected String alternateItemID;
    @XmlAttribute(name = "BundleFulfillmentMode")
    protected String bundleFulfillmentMode;
    @XmlAttribute(name = "CostCurrency")
    protected String costCurrency;
    @XmlAttribute(name = "CountryOfOrigin")
    protected String countryOfOrigin;
    @XmlAttribute(name = "CustomerItem")
    protected String customerItem;
    @XmlAttribute(name = "CustomerItemDesc")
    protected String customerItemDesc;
    @XmlAttribute(name = "ECCNNo")
    protected String eccnNo;
    @XmlAttribute(name = "HarmonizedCode")
    protected String harmonizedCode;
    @XmlAttribute(name = "ISBN")
    protected String isbn;
    @XmlAttribute(name = "ItemDesc")
    @JsonProperty("ItemDesc")
    protected String itemDesc;
    @XmlAttribute(name = "ItemID")
    @JsonProperty("ItemID")
    protected String itemID;
    @XmlAttribute(name = "ItemShortDesc")
    protected String itemShortDesc;
    @XmlAttribute(name = "ItemWeight")
    protected BigDecimal itemWeight;
    @XmlAttribute(name = "ItemWeightUOM")
    protected String itemWeightUOM;
    @XmlAttribute(name = "ManufacturerItem")
    protected String manufacturerItem;
    @XmlAttribute(name = "ManufacturerItemDesc")
    protected String manufacturerItemDesc;
    @XmlAttribute(name = "ManufacturerName")
    protected String manufacturerName;
    @XmlAttribute(name = "NMFCClass")
    protected String nmfcClass;
    @XmlAttribute(name = "NMFCCode")
    protected String nmfcCode;
    @XmlAttribute(name = "NMFCDescription")
    protected String nmfcDescription;
    @XmlAttribute(name = "ProductClass")
    protected String productClass;
    @XmlAttribute(name = "ProductLine")
    protected String productLine;
    @XmlAttribute(name = "ScheduleBCode")
    protected String scheduleBCode;
    @XmlAttribute(name = "SupplierItem")
    protected String supplierItem;
    @XmlAttribute(name = "SupplierItemDesc")
    protected String supplierItemDesc;
    @XmlAttribute(name = "TaxProductCode")
    protected String taxProductCode;
    @XmlAttribute(name = "UPCCode")
    protected String upcCode;
    @XmlAttribute(name = "UnitCost")
    protected BigDecimal unitCost;
    @XmlAttribute(name = "UnitOfMeasure")
    protected String unitOfMeasure;

    /**
     * Gets the value of the alternateItemID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlternateItemID() {
        return alternateItemID;
    }

    /**
     * Sets the value of the alternateItemID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlternateItemID(String value) {
        this.alternateItemID = value;
    }

    /**
     * Gets the value of the bundleFulfillmentMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBundleFulfillmentMode() {
        return bundleFulfillmentMode;
    }

    /**
     * Sets the value of the bundleFulfillmentMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBundleFulfillmentMode(String value) {
        this.bundleFulfillmentMode = value;
    }

    /**
     * Gets the value of the costCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCostCurrency() {
        return costCurrency;
    }

    /**
     * Sets the value of the costCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCostCurrency(String value) {
        this.costCurrency = value;
    }

    /**
     * Gets the value of the countryOfOrigin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryOfOrigin() {
        return countryOfOrigin;
    }

    /**
     * Sets the value of the countryOfOrigin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryOfOrigin(String value) {
        this.countryOfOrigin = value;
    }

    /**
     * Gets the value of the customerItem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerItem() {
        return customerItem;
    }

    /**
     * Sets the value of the customerItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerItem(String value) {
        this.customerItem = value;
    }

    /**
     * Gets the value of the customerItemDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerItemDesc() {
        return customerItemDesc;
    }

    /**
     * Sets the value of the customerItemDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerItemDesc(String value) {
        this.customerItemDesc = value;
    }

    /**
     * Gets the value of the eccnNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getECCNNo() {
        return eccnNo;
    }

    /**
     * Sets the value of the eccnNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setECCNNo(String value) {
        this.eccnNo = value;
    }

    /**
     * Gets the value of the harmonizedCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHarmonizedCode() {
        return harmonizedCode;
    }

    /**
     * Sets the value of the harmonizedCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHarmonizedCode(String value) {
        this.harmonizedCode = value;
    }

    /**
     * Gets the value of the isbn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISBN() {
        return isbn;
    }

    /**
     * Sets the value of the isbn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISBN(String value) {
        this.isbn = value;
    }

    /**
     * Gets the value of the itemDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemDesc() {
        return itemDesc;
    }

    /**
     * Sets the value of the itemDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemDesc(String value) {
        this.itemDesc = value;
    }

    /**
     * Gets the value of the itemID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemID() {
        return itemID;
    }

    /**
     * Sets the value of the itemID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemID(String value) {
        this.itemID = value;
    }

    /**
     * Gets the value of the itemShortDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemShortDesc() {
        return itemShortDesc;
    }

    /**
     * Sets the value of the itemShortDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemShortDesc(String value) {
        this.itemShortDesc = value;
    }

    /**
     * Gets the value of the itemWeight property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getItemWeight() {
        return itemWeight;
    }

    /**
     * Sets the value of the itemWeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setItemWeight(BigDecimal value) {
        this.itemWeight = value;
    }

    /**
     * Gets the value of the itemWeightUOM property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemWeightUOM() {
        return itemWeightUOM;
    }

    /**
     * Sets the value of the itemWeightUOM property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemWeightUOM(String value) {
        this.itemWeightUOM = value;
    }

    /**
     * Gets the value of the manufacturerItem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getManufacturerItem() {
        return manufacturerItem;
    }

    /**
     * Sets the value of the manufacturerItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setManufacturerItem(String value) {
        this.manufacturerItem = value;
    }

    /**
     * Gets the value of the manufacturerItemDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getManufacturerItemDesc() {
        return manufacturerItemDesc;
    }

    /**
     * Sets the value of the manufacturerItemDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setManufacturerItemDesc(String value) {
        this.manufacturerItemDesc = value;
    }

    /**
     * Gets the value of the manufacturerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getManufacturerName() {
        return manufacturerName;
    }

    /**
     * Sets the value of the manufacturerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setManufacturerName(String value) {
        this.manufacturerName = value;
    }

    /**
     * Gets the value of the nmfcClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNMFCClass() {
        return nmfcClass;
    }

    /**
     * Sets the value of the nmfcClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNMFCClass(String value) {
        this.nmfcClass = value;
    }

    /**
     * Gets the value of the nmfcCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNMFCCode() {
        return nmfcCode;
    }

    /**
     * Sets the value of the nmfcCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNMFCCode(String value) {
        this.nmfcCode = value;
    }

    /**
     * Gets the value of the nmfcDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNMFCDescription() {
        return nmfcDescription;
    }

    /**
     * Sets the value of the nmfcDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNMFCDescription(String value) {
        this.nmfcDescription = value;
    }

    /**
     * Gets the value of the productClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductClass() {
        return productClass;
    }

    /**
     * Sets the value of the productClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductClass(String value) {
        this.productClass = value;
    }

    /**
     * Gets the value of the productLine property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductLine() {
        return productLine;
    }

    /**
     * Sets the value of the productLine property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductLine(String value) {
        this.productLine = value;
    }

    /**
     * Gets the value of the scheduleBCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScheduleBCode() {
        return scheduleBCode;
    }

    /**
     * Sets the value of the scheduleBCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScheduleBCode(String value) {
        this.scheduleBCode = value;
    }

    /**
     * Gets the value of the supplierItem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupplierItem() {
        return supplierItem;
    }

    /**
     * Sets the value of the supplierItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupplierItem(String value) {
        this.supplierItem = value;
    }

    /**
     * Gets the value of the supplierItemDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupplierItemDesc() {
        return supplierItemDesc;
    }

    /**
     * Sets the value of the supplierItemDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupplierItemDesc(String value) {
        this.supplierItemDesc = value;
    }

    /**
     * Gets the value of the taxProductCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxProductCode() {
        return taxProductCode;
    }

    /**
     * Sets the value of the taxProductCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxProductCode(String value) {
        this.taxProductCode = value;
    }

    /**
     * Gets the value of the upcCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUPCCode() {
        return upcCode;
    }

    /**
     * Sets the value of the upcCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUPCCode(String value) {
        this.upcCode = value;
    }

    /**
     * Gets the value of the unitCost property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getUnitCost() {
        return unitCost;
    }

    /**
     * Sets the value of the unitCost property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setUnitCost(BigDecimal value) {
        this.unitCost = value;
    }

    /**
     * Gets the value of the unitOfMeasure property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnitOfMeasure() {
        return unitOfMeasure;
    }

    /**
     * Sets the value of the unitOfMeasure property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnitOfMeasure(String value) {
        this.unitOfMeasure = value;
    }

}
