//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.25 at 03:34:08 AM GMT 
//


package com.tesco.ofs.order.representation;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{http://www.sterlingcommerce.com/documentation/YFS/createOrder/input}KitLineTranQuantity" minOccurs="0"/>
 *       &lt;/all>
 *       &lt;attribute name="CustomerItem" type="{http://www.sterlingcommerce.com/documentation/types}Text-40" />
 *       &lt;attribute name="CustomerItemDesc" type="{http://www.sterlingcommerce.com/documentation/types}Text-500" />
 *       &lt;attribute name="DepartmentCode" type="{http://www.sterlingcommerce.com/documentation/types}Text-20" />
 *       &lt;attribute name="ItemDesc" type="{http://www.sterlingcommerce.com/documentation/types}Text-500" />
 *       &lt;attribute name="ItemID" use="required" type="{http://www.sterlingcommerce.com/documentation/types}ItemID" />
 *       &lt;attribute name="ItemShortDesc" type="{http://www.sterlingcommerce.com/documentation/types}Text-200" />
 *       &lt;attribute name="ItemWeight" type="{http://www.sterlingcommerce.com/documentation/types}Dimension" />
 *       &lt;attribute name="ItemWeightUOM" type="{http://www.sterlingcommerce.com/documentation/types}UOM" />
 *       &lt;attribute name="KitQty" use="required" type="{http://www.sterlingcommerce.com/documentation/types}Quantity" />
 *       &lt;attribute name="ProductClass" type="{http://www.sterlingcommerce.com/documentation/types}ProductClass" />
 *       &lt;attribute name="SupplierItem" type="{http://www.sterlingcommerce.com/documentation/types}Text-40" />
 *       &lt;attribute name="SupplierItemDesc" type="{http://www.sterlingcommerce.com/documentation/types}ItemDesc" />
 *       &lt;attribute name="UPCCode" type="{http://www.sterlingcommerce.com/documentation/types}Text-40" />
 *       &lt;attribute name="UnitCost" type="{http://www.sterlingcommerce.com/documentation/types}UnitPrice" />
 *       &lt;attribute name="UnitOfMeasure" type="{http://www.sterlingcommerce.com/documentation/types}UOM" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "KitLine")
public class KitLine {

    @XmlElement(name = "KitLineTranQuantity")
    protected KitLineTranQuantity kitLineTranQuantity;
    @XmlAttribute(name = "CustomerItem")
    protected String customerItem;
    @XmlAttribute(name = "CustomerItemDesc")
    protected String customerItemDesc;
    @XmlAttribute(name = "DepartmentCode")
    protected String departmentCode;
    @XmlAttribute(name = "ItemDesc")
    protected String itemDesc;
    @XmlAttribute(name = "ItemID", required = true)
    protected String itemID;
    @XmlAttribute(name = "ItemShortDesc")
    protected String itemShortDesc;
    @XmlAttribute(name = "ItemWeight")
    protected BigDecimal itemWeight;
    @XmlAttribute(name = "ItemWeightUOM")
    protected String itemWeightUOM;
    @XmlAttribute(name = "KitQty", required = true)
    protected BigDecimal kitQty;
    @XmlAttribute(name = "ProductClass")
    protected String productClass;
    @XmlAttribute(name = "SupplierItem")
    protected String supplierItem;
    @XmlAttribute(name = "SupplierItemDesc")
    protected String supplierItemDesc;
    @XmlAttribute(name = "UPCCode")
    protected String upcCode;
    @XmlAttribute(name = "UnitCost")
    protected BigDecimal unitCost;
    @XmlAttribute(name = "UnitOfMeasure")
    protected String unitOfMeasure;

    /**
     * Gets the value of the kitLineTranQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link KitLineTranQuantity }
     *     
     */
    public KitLineTranQuantity getKitLineTranQuantity() {
        return kitLineTranQuantity;
    }

    /**
     * Sets the value of the kitLineTranQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link KitLineTranQuantity }
     *     
     */
    public void setKitLineTranQuantity(KitLineTranQuantity value) {
        this.kitLineTranQuantity = value;
    }

    /**
     * Gets the value of the customerItem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerItem() {
        return customerItem;
    }

    /**
     * Sets the value of the customerItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerItem(String value) {
        this.customerItem = value;
    }

    /**
     * Gets the value of the customerItemDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerItemDesc() {
        return customerItemDesc;
    }

    /**
     * Sets the value of the customerItemDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerItemDesc(String value) {
        this.customerItemDesc = value;
    }

    /**
     * Gets the value of the departmentCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepartmentCode() {
        return departmentCode;
    }

    /**
     * Sets the value of the departmentCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepartmentCode(String value) {
        this.departmentCode = value;
    }

    /**
     * Gets the value of the itemDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemDesc() {
        return itemDesc;
    }

    /**
     * Sets the value of the itemDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemDesc(String value) {
        this.itemDesc = value;
    }

    /**
     * Gets the value of the itemID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemID() {
        return itemID;
    }

    /**
     * Sets the value of the itemID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemID(String value) {
        this.itemID = value;
    }

    /**
     * Gets the value of the itemShortDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemShortDesc() {
        return itemShortDesc;
    }

    /**
     * Sets the value of the itemShortDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemShortDesc(String value) {
        this.itemShortDesc = value;
    }

    /**
     * Gets the value of the itemWeight property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getItemWeight() {
        return itemWeight;
    }

    /**
     * Sets the value of the itemWeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setItemWeight(BigDecimal value) {
        this.itemWeight = value;
    }

    /**
     * Gets the value of the itemWeightUOM property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemWeightUOM() {
        return itemWeightUOM;
    }

    /**
     * Sets the value of the itemWeightUOM property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemWeightUOM(String value) {
        this.itemWeightUOM = value;
    }

    /**
     * Gets the value of the kitQty property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getKitQty() {
        return kitQty;
    }

    /**
     * Sets the value of the kitQty property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setKitQty(BigDecimal value) {
        this.kitQty = value;
    }

    /**
     * Gets the value of the productClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductClass() {
        return productClass;
    }

    /**
     * Sets the value of the productClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductClass(String value) {
        this.productClass = value;
    }

    /**
     * Gets the value of the supplierItem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupplierItem() {
        return supplierItem;
    }

    /**
     * Sets the value of the supplierItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupplierItem(String value) {
        this.supplierItem = value;
    }

    /**
     * Gets the value of the supplierItemDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupplierItemDesc() {
        return supplierItemDesc;
    }

    /**
     * Sets the value of the supplierItemDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupplierItemDesc(String value) {
        this.supplierItemDesc = value;
    }

    /**
     * Gets the value of the upcCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUPCCode() {
        return upcCode;
    }

    /**
     * Sets the value of the upcCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUPCCode(String value) {
        this.upcCode = value;
    }

    /**
     * Gets the value of the unitCost property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getUnitCost() {
        return unitCost;
    }

    /**
     * Sets the value of the unitCost property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setUnitCost(BigDecimal value) {
        this.unitCost = value;
    }

    /**
     * Gets the value of the unitOfMeasure property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnitOfMeasure() {
        return unitOfMeasure;
    }

    /**
     * Sets the value of the unitOfMeasure property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnitOfMeasure(String value) {
        this.unitOfMeasure = value;
    }

}
