//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.25 at 03:34:08 AM GMT 
//


package com.tesco.ofs.order.representation;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="DiscountPercentage" type="{http://www.sterlingcommerce.com/documentation/types}Percentage" />
 *       &lt;attribute name="IsLinePriceForInformationOnly" type="{http://www.sterlingcommerce.com/documentation/types}Flag" />
 *       &lt;attribute name="IsPriceLocked" type="{http://www.sterlingcommerce.com/documentation/types}Flag" />
 *       &lt;attribute name="ListPrice" type="{http://www.sterlingcommerce.com/documentation/types}UnitPrice" />
 *       &lt;attribute name="PricingQtyConversionFactor" type="{http://www.sterlingcommerce.com/documentation/types}Quantity" />
 *       &lt;attribute name="PricingQuantityStrategy" type="{http://www.sterlingcommerce.com/documentation/types}EnumPricingQuantityStrategy" />
 *       &lt;attribute name="PricingUOM" type="{http://www.sterlingcommerce.com/documentation/types}UOM" />
 *       &lt;attribute name="RetailPrice" type="{http://www.sterlingcommerce.com/documentation/types}UnitPrice" />
 *       &lt;attribute name="TaxExemptionCertificate" type="{http://www.sterlingcommerce.com/documentation/types}Text-40" />
 *       &lt;attribute name="TaxableFlag" type="{http://www.sterlingcommerce.com/documentation/types}Flag" />
 *       &lt;attribute name="UnitPrice" type="{http://www.sterlingcommerce.com/documentation/types}UnitPrice" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "LinePriceInfo")
public class LinePriceInfo {

    @XmlAttribute(name = "DiscountPercentage")
    protected BigDecimal discountPercentage;
    @XmlAttribute(name = "IsLinePriceForInformationOnly")
    protected String isLinePriceForInformationOnly;
    @XmlAttribute(name = "IsPriceLocked")
    protected String isPriceLocked;
    @XmlAttribute(name = "ListPrice")
    protected BigDecimal listPrice;
    @XmlAttribute(name = "PricingQtyConversionFactor")
    protected BigDecimal pricingQtyConversionFactor;
    @XmlAttribute(name = "PricingQuantityStrategy")
    protected String pricingQuantityStrategy;
    @XmlAttribute(name = "PricingUOM")
    protected String pricingUOM;
    @XmlAttribute(name = "RetailPrice")
    protected BigDecimal retailPrice;
    @XmlAttribute(name = "TaxExemptionCertificate")
    protected String taxExemptionCertificate;
    @XmlAttribute(name = "TaxableFlag")
    protected String taxableFlag;
    @XmlAttribute(name = "UnitPrice")
    protected BigDecimal unitPrice;

    /**
     * Gets the value of the discountPercentage property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDiscountPercentage() {
        return discountPercentage;
    }

    /**
     * Sets the value of the discountPercentage property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDiscountPercentage(BigDecimal value) {
        this.discountPercentage = value;
    }

    /**
     * Gets the value of the isLinePriceForInformationOnly property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsLinePriceForInformationOnly() {
        return isLinePriceForInformationOnly;
    }

    /**
     * Sets the value of the isLinePriceForInformationOnly property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsLinePriceForInformationOnly(String value) {
        this.isLinePriceForInformationOnly = value;
    }

    /**
     * Gets the value of the isPriceLocked property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsPriceLocked() {
        return isPriceLocked;
    }

    /**
     * Sets the value of the isPriceLocked property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsPriceLocked(String value) {
        this.isPriceLocked = value;
    }

    /**
     * Gets the value of the listPrice property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getListPrice() {
        return listPrice;
    }

    /**
     * Sets the value of the listPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setListPrice(BigDecimal value) {
        this.listPrice = value;
    }

    /**
     * Gets the value of the pricingQtyConversionFactor property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPricingQtyConversionFactor() {
        return pricingQtyConversionFactor;
    }

    /**
     * Sets the value of the pricingQtyConversionFactor property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPricingQtyConversionFactor(BigDecimal value) {
        this.pricingQtyConversionFactor = value;
    }

    /**
     * Gets the value of the pricingQuantityStrategy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPricingQuantityStrategy() {
        return pricingQuantityStrategy;
    }

    /**
     * Sets the value of the pricingQuantityStrategy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPricingQuantityStrategy(String value) {
        this.pricingQuantityStrategy = value;
    }

    /**
     * Gets the value of the pricingUOM property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPricingUOM() {
        return pricingUOM;
    }

    /**
     * Sets the value of the pricingUOM property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPricingUOM(String value) {
        this.pricingUOM = value;
    }

    /**
     * Gets the value of the retailPrice property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRetailPrice() {
        return retailPrice;
    }

    /**
     * Sets the value of the retailPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRetailPrice(BigDecimal value) {
        this.retailPrice = value;
    }

    /**
     * Gets the value of the taxExemptionCertificate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxExemptionCertificate() {
        return taxExemptionCertificate;
    }

    /**
     * Sets the value of the taxExemptionCertificate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxExemptionCertificate(String value) {
        this.taxExemptionCertificate = value;
    }

    /**
     * Gets the value of the taxableFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxableFlag() {
        return taxableFlag;
    }

    /**
     * Sets the value of the taxableFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxableFlag(String value) {
        this.taxableFlag = value;
    }

    /**
     * Gets the value of the unitPrice property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getUnitPrice() {
        return unitPrice;
    }

    /**
     * Sets the value of the unitPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setUnitPrice(BigDecimal value) {
        this.unitPrice = value;
    }

}
