//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.25 at 03:34:08 AM GMT 
//


package com.tesco.ofs.order.representation;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.tesco.ofs.order.representation package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Order_QNAME = new QName("http://www.sterlingcommerce.com/documentation/YFS/createOrder/input", "Order");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.tesco.ofs.order.representation
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link OrderAuditLevel }
     * 
     */
    public OrderAuditLevel createOrderAuditLevel() {
        return new OrderAuditLevel();
    }

    /**
     * Create an instance of {@link OrderAuditDetails }
     * 
     */
    public OrderAuditDetails createOrderAuditDetails() {
        return new OrderAuditDetails();
    }

    /**
     * Create an instance of {@link PaymentMethod }
     * 
     */
    public PaymentMethod createPaymentMethod() {
        return new PaymentMethod();
    }

    /**
     * Create an instance of {@link PaymentDetailsList }
     * 
     */
    public PaymentDetailsList createPaymentDetailsList() {
        return new PaymentDetailsList();
    }

    /**
     * Create an instance of {@link OrderLine }
     * 
     */
    public OrderLines createOrderLines() {
        return new OrderLines();
    }

    /**
     * Create an instance of {@link CustomAuditDetails }
     * 
     */
    public CustomAuditDetails createCustomAuditDetails() {
        return new CustomAuditDetails();
    }

    /**
     * Create an instance of {@link OrderLineOption }
     * 
     */
    public OrderLineOption createOrderLineOption() {
        return new OrderLineOption();
    }

    /**
     * Create an instance of {@link Opportunity }
     * 
     */
    public Opportunity createOpportunity() {
        return new Opportunity();
    }

    /**
     * Create an instance of {@link Opportunity.Notes }
     * 
     */
    public Opportunity.Notes createOpportunityNotes() {
        return new Opportunity.Notes();
    }

    /**
     * Create an instance of {@link CustomAuditDetails.OrderAuditDetail }
     * 
     */
    public CustomAuditDetails.OrderAuditDetail createCustomAuditDetailsOrderAuditDetail() {
        return new CustomAuditDetails.OrderAuditDetail();
    }

    /**
     * Create an instance of {@link CustomAuditDetails.OrderAuditDetail.Attributes }
     * 
     */
    public CustomAuditDetails.OrderAuditDetail.Attributes createCustomAuditDetailsOrderAuditDetailAttributes() {
        return new CustomAuditDetails.OrderAuditDetail.Attributes();
    }

    /**
     * Create an instance of {@link CustomAuditDetails.OrderAuditDetail.IDs }
     * 
     */
    public CustomAuditDetails.OrderAuditDetail.IDs createCustomAuditDetailsOrderAuditDetailIDs() {
        return new CustomAuditDetails.OrderAuditDetail.IDs();
    }

    /**
     * Create an instance of {@link OrderLines.OrderLine }
     * 
     */
    public OrderLines.OrderLine createOrderLinesOrderLine() {
        return new OrderLines.OrderLine();
    }

    /**
     * Create an instance of {@link OrderLines.OrderLine.OrderHoldTypes }
     * 
     */
    public OrderLines.OrderLine.OrderHoldTypes createOrderLinesOrderLineOrderHoldTypes() {
        return new OrderLines.OrderLine.OrderHoldTypes();
    }

    /**
     * Create an instance of {@link OrderLines.OrderLine.Notes }
     * 
     */
    public OrderLines.OrderLine.Notes createOrderLinesOrderLineNotes() {
        return new OrderLines.OrderLine.Notes();
    }

    /**
     * Create an instance of {@link OrderLines.OrderLine.Awards }
     * 
     */
    public OrderLines.OrderLine.Awards createOrderLinesOrderLineAwards() {
        return new OrderLines.OrderLine.Awards();
    }

    /**
     * Create an instance of {@link OrderLines.OrderLine.Awards.Award }
     * 
     */
    public OrderLines.OrderLine.Awards.Award createOrderLinesOrderLineAwardsAward() {
        return new OrderLines.OrderLine.Awards.Award();
    }

    /**
     * Create an instance of {@link OrderLines.OrderLine.Awards.Award.PromotionReferences }
     * 
     */
    public OrderLines.OrderLine.Awards.Award.PromotionReferences createOrderLinesOrderLineAwardsAwardPromotionReferences() {
        return new OrderLines.OrderLine.Awards.Award.PromotionReferences();
    }

    /**
     * Create an instance of {@link OrderLines.OrderLine.Promotions }
     * 
     */
    public OrderLines.OrderLine.Promotions createOrderLinesOrderLinePromotions() {
        return new OrderLines.OrderLine.Promotions();
    }

    /**
     * Create an instance of {@link OrderLines.OrderLine.OrderDates }
     * 
     */
    public OrderLines.OrderLine.OrderDates createOrderLinesOrderLineOrderDates() {
        return new OrderLines.OrderLine.OrderDates();
    }

    /**
     * Create an instance of {@link OrderLines.OrderLine.AdditionalAddresses }
     * 
     */
    public OrderLines.OrderLine.AdditionalAddresses createOrderLinesOrderLineAdditionalAddresses() {
        return new OrderLines.OrderLine.AdditionalAddresses();
    }

    /**
     * Create an instance of {@link OrderLines.OrderLine.AdditionalAddresses.AdditionalAddress }
     * 
     */
    public OrderLines.OrderLine.AdditionalAddresses.AdditionalAddress createOrderLinesOrderLineAdditionalAddressesAdditionalAddress() {
        return new OrderLines.OrderLine.AdditionalAddresses.AdditionalAddress();
    }

    /**
     * Create an instance of {@link OrderLines.OrderLine.References }
     * 
     */
    public OrderLines.OrderLine.References createOrderLinesOrderLineReferences() {
        return new OrderLines.OrderLine.References();
    }

    /**
     * Create an instance of {@link OrderLines.OrderLine.Instructions }
     * 
     */
    public OrderLines.OrderLine.Instructions createOrderLinesOrderLineInstructions() {
        return new OrderLines.OrderLine.Instructions();
    }

    /**
     * Create an instance of {@link FulfillmentOrderBean }
     * 
     */
    public FulfillmentOrderBean createOrderXSDType() {
        return new FulfillmentOrderBean();
    }

    /**
     * Create an instance of {@link FulfillmentOrderBean.Awards }
     * 
     */
    public FulfillmentOrderBean.Awards createOrderXSDTypeAwards() {
        return new FulfillmentOrderBean.Awards();
    }

    /**
     * Create an instance of {@link FulfillmentOrderBean.Promotions }
     * 
     */
    public FulfillmentOrderBean.Promotions createOrderXSDTypePromotions() {
        return new FulfillmentOrderBean.Promotions();
    }

    /**
     * Create an instance of {@link FulfillmentOrderBean.Promotions.Promotion }
     * 
     */
    public FulfillmentOrderBean.Promotions.Promotion createOrderXSDTypePromotionsPromotion() {
        return new FulfillmentOrderBean.Promotions.Promotion();
    }

    /**
     * Create an instance of {@link FulfillmentOrderBean.Promotions.Promotion.PromotionReferences }
     * 
     */
    public FulfillmentOrderBean.Promotions.Promotion.PromotionReferences createOrderXSDTypePromotionsPromotionPromotionReferences() {
        return new FulfillmentOrderBean.Promotions.Promotion.PromotionReferences();
    }

    /**
     * Create an instance of {@link FulfillmentOrderBean.OrderHoldTypes }
     * 
     */
    public FulfillmentOrderBean.OrderHoldTypes createOrderXSDTypeOrderHoldTypes() {
        return new FulfillmentOrderBean.OrderHoldTypes();
    }

    /**
     * Create an instance of {@link FulfillmentOrderBean.OrderDates }
     * 
     */
    public FulfillmentOrderBean.OrderDates createOrderXSDTypeOrderDates() {
        return new FulfillmentOrderBean.OrderDates();
    }

    /**
     * Create an instance of {@link FulfillmentOrderBean.References }
     * 
     */
    public FulfillmentOrderBean.References createOrderXSDTypeReferences() {
        return new FulfillmentOrderBean.References();
    }

    /**
     * Create an instance of {@link FulfillmentOrderBean.AdditionalAddresses }
     * 
     */
    public FulfillmentOrderBean.AdditionalAddresses createOrderXSDTypeAdditionalAddresses() {
        return new FulfillmentOrderBean.AdditionalAddresses();
    }

    /**
     * Create an instance of {@link FulfillmentOrderBean.AdditionalAddresses.AdditionalAddress }
     * 
     */
    public FulfillmentOrderBean.AdditionalAddresses.AdditionalAddress createOrderXSDTypeAdditionalAddressesAdditionalAddress() {
        return new FulfillmentOrderBean.AdditionalAddresses.AdditionalAddress();
    }

    /**
     * Create an instance of {@link FulfillmentOrderBean.Instructions }
     * 
     */
    public FulfillmentOrderBean.Instructions createOrderXSDTypeInstructions() {
        return new FulfillmentOrderBean.Instructions();
    }

    /**
     * Create an instance of {@link FulfillmentOrderBean.Notes }
     * 
     */
    public FulfillmentOrderBean.Notes createOrderXSDTypeNotes() {
        return new FulfillmentOrderBean.Notes();
    }

    /**
     * Create an instance of {@link OrderAuditDetails.OrderAuditDetail }
     * 
     */
    public OrderAuditDetails.OrderAuditDetail createOrderAuditDetailsOrderAuditDetail() {
        return new OrderAuditDetails.OrderAuditDetail();
    }

    /**
     * Create an instance of {@link OrderAuditDetails.OrderAuditDetail.Attributes }
     * 
     */
    public OrderAuditDetails.OrderAuditDetail.Attributes createOrderAuditDetailsOrderAuditDetailAttributes() {
        return new OrderAuditDetails.OrderAuditDetail.Attributes();
    }

    /**
     * Create an instance of {@link OrderAuditDetails.OrderAuditDetail.IDs }
     * 
     */
    public OrderAuditDetails.OrderAuditDetail.IDs createOrderAuditDetailsOrderAuditDetailIDs() {
        return new OrderAuditDetails.OrderAuditDetail.IDs();
    }

    /**
     * Create an instance of {@link OrderAuditLevel.OrderLine }
     * 
     */
    public OrderAuditLevel.OrderLine createOrderAuditLevelOrderLine() {
        return new OrderAuditLevel.OrderLine();
    }

    /**
     * Create an instance of {@link ModificationTypes }
     * 
     */
    public ModificationTypes createModificationTypes() {
        return new ModificationTypes();
    }

    /**
     * Create an instance of {@link ModificationType }
     * 
     */
    public ModificationType createModificationType() {
        return new ModificationType();
    }

    /**
     * Create an instance of {@link HeaderCharges }
     * 
     */
    public HeaderCharges createHeaderCharges() {
        return new HeaderCharges();
    }

    /**
     * Create an instance of {@link HeaderCharge }
     * 
     */
    public HeaderCharge createHeaderCharge() {
        return new HeaderCharge();
    }

    /**
     * Create an instance of {@link LineCharges }
     * 
     */
    public LineCharges createLineCharges() {
        return new LineCharges();
    }

    /**
     * Create an instance of {@link LineCharge }
     * 
     */
    public LineCharge createLineCharge() {
        return new LineCharge();
    }

    /**
     * Create an instance of {@link ReturnOrderForExchange }
     * 
     */
    public ReturnOrderForExchange createReturnOrderForExchange() {
        return new ReturnOrderForExchange();
    }

    /**
     * Create an instance of {@link OrderLineRelationships }
     * 
     */
    public OrderLineRelationships createOrderLineRelationships() {
        return new OrderLineRelationships();
    }

    /**
     * Create an instance of {@link OrderLineRelationship }
     * 
     */
    public OrderLineRelationship createOrderLineRelationship() {
        return new OrderLineRelationship();
    }

    /**
     * Create an instance of {@link ParentLine }
     * 
     */
    public ParentLine createParentLine() {
        return new ParentLine();
    }

    /**
     * Create an instance of {@link ChildLine }
     * 
     */
    public ChildLine createChildLine() {
        return new ChildLine();
    }

    /**
     * Create an instance of {@link HeaderTax }
     * 
     */
    public HeaderTax createHeaderTax() {
        return new HeaderTax();
    }

    /**
     * Create an instance of {@link FileAttachment }
     * 
     */
    public FileAttachment createFileAttachment() {
        return new FileAttachment();
    }

    /**
     * Create an instance of {@link SpecialServices }
     * 
     */
    public SpecialServices createSpecialServices() {
        return new SpecialServices();
    }

    /**
     * Create an instance of {@link SpecialService }
     * 
     */
    public SpecialService createSpecialService() {
        return new SpecialService();
    }

    /**
     * Create an instance of {@link OrderAudit }
     * 
     */
    public OrderAudit createOrderAudit() {
        return new OrderAudit();
    }

    /**
     * Create an instance of {@link OrderAuditLevels }
     * 
     */
    public OrderAuditLevels createOrderAuditLevels() {
        return new OrderAuditLevels();
    }

    /**
     * Create an instance of {@link PaymentMethods }
     * 
     */
    public PaymentMethods createPaymentMethods() {
        return new PaymentMethods();
    }

    /**
     * Create an instance of {@link PaymentMethod.PaymentDetails }
     * 
     */
    public PaymentMethod.PaymentDetails createPaymentMethodPaymentDetails() {
        return new PaymentMethod.PaymentDetails();
    }

    /**
     * Create an instance of {@link PaymentDetailsList.PaymentDetails }
     * 
     */
    public PaymentDetailsList.PaymentDetails createPaymentDetailsListPaymentDetails() {
        return new PaymentDetailsList.PaymentDetails();
    }

    /**
     * Create an instance of {@link PaymentMethod.PersonInfoBillTo }
     * 
     */
    public PaymentMethod.PersonInfoBillTo createPaymentMethodPersonInfoBillTo() {
        return new PaymentMethod.PersonInfoBillTo();
    }

    /**
     * Create an instance of {@link Item }
     * 
     */
    public Item createItem() {
        return new Item();
    }

    /**
     * Create an instance of {@link ProductServiceAssoc }
     * 
     */
    public ProductServiceAssoc createProductServiceAssoc() {
        return new ProductServiceAssoc();
    }

    /**
     * Create an instance of {@link ProductLine }
     * 
     */
    public ProductLine createProductLine() {
        return new ProductLine();
    }

    /**
     * Create an instance of {@link ServiceLine }
     * 
     */
    public ServiceLine createServiceLine() {
        return new ServiceLine();
    }

    /**
     * Create an instance of {@link OrderLineSourcingControls }
     * 
     */
    public OrderLineSourcingControls createOrderLineSourcingControls() {
        return new OrderLineSourcingControls();
    }

    /**
     * Create an instance of {@link OrderLineSourcingCntrl }
     * 
     */
    public OrderLineSourcingCntrl createOrderLineSourcingCntrl() {
        return new OrderLineSourcingCntrl();
    }

    /**
     * Create an instance of {@link LineTaxes }
     * 
     */
    public LineTaxes createLineTaxes() {
        return new LineTaxes();
    }

    /**
     * Create an instance of {@link LineTax }
     * 
     */
    public LineTax createLineTax() {
        return new LineTax();
    }

    /**
     * Create an instance of {@link ChainedFrom }
     * 
     */
    public ChainedFrom createChainedFrom() {
        return new ChainedFrom();
    }

    /**
     * Create an instance of {@link OrderLineReservation }
     * 
     */
    public OrderLineReservation createOrderLineReservation() {
        return new OrderLineReservation();
    }

    /**
     * Create an instance of {@link Dependency }
     * 
     */
    public Dependency createDependency() {
        return new Dependency();
    }

    /**
     * Create an instance of {@link OrderAudits }
     * 
     */
    public OrderAudits createOrderAudits() {
        return new OrderAudits();
    }

    /**
     * Create an instance of {@link HeaderTaxes }
     * 
     */
    public HeaderTaxes createHeaderTaxes() {
        return new HeaderTaxes();
    }

    /**
     * Create an instance of {@link BuyerContactAddress }
     * 
     */
    public BuyerContactAddress createBuyerContactAddress() {
        return new BuyerContactAddress();
    }

    /**
     * Create an instance of {@link ProductItems }
     * 
     */
    public ProductItems createProductItems() {
        return new ProductItems();
    }

    /**
     * Create an instance of {@link ProductItem }
     * 
     */
    public ProductItem createProductItem() {
        return new ProductItem();
    }

    /**
     * Create an instance of {@link Schedules }
     * 
     */
    public Schedules createSchedules() {
        return new Schedules();
    }

    /**
     * Create an instance of {@link Schedule }
     * 
     */
    public Schedule createSchedule() {
        return new Schedule();
    }

    /**
     * Create an instance of {@link ScheduleTranQuantity }
     * 
     */
    public ScheduleTranQuantity createScheduleTranQuantity() {
        return new ScheduleTranQuantity();
    }

    /**
     * Create an instance of {@link BundleParentLine }
     * 
     */
    public BundleParentLine createBundleParentLine() {
        return new BundleParentLine();
    }

    /**
     * Create an instance of {@link ProductServiceAssocs }
     * 
     */
    public ProductServiceAssocs createProductServiceAssocs() {
        return new ProductServiceAssocs();
    }

    /**
     * Create an instance of {@link FileAttachments }
     * 
     */
    public FileAttachments createFileAttachments() {
        return new FileAttachments();
    }

    /**
     * Create an instance of {@link AnswerSet }
     * 
     */
    public AnswerSet createAnswerSet() {
        return new AnswerSet();
    }

    /**
     * Create an instance of {@link Answers }
     * 
     */
    public Answers createAnswers() {
        return new Answers();
    }

    /**
     * Create an instance of {@link Answer }
     * 
     */
    public Answer createAnswer() {
        return new Answer();
    }

    /**
     * Create an instance of {@link OrderLineTranQuantity }
     * 
     */
    public OrderLineTranQuantity createOrderLineTranQuantity() {
        return new OrderLineTranQuantity();
    }

    /**
     * Create an instance of {@link OrderSearchCondition }
     * 
     */
    public OrderSearchCondition createOrderSearchCondition() {
        return new OrderSearchCondition();
    }

    /**
     * Create an instance of {@link AnswerSets }
     * 
     */
    public AnswerSets createAnswerSets() {
        return new AnswerSets();
    }

    /**
     * Create an instance of {@link PriceInfo }
     * 
     */
    public PriceInfo createPriceInfo() {
        return new PriceInfo();
    }

    /**
     * Create an instance of {@link KitLines }
     * 
     */
    public KitLines createKitLines() {
        return new KitLines();
    }

    /**
     * Create an instance of {@link KitLine }
     * 
     */
    public KitLine createKitLine() {
        return new KitLine();
    }

    /**
     * Create an instance of {@link KitLineTranQuantity }
     * 
     */
    public KitLineTranQuantity createKitLineTranQuantity() {
        return new KitLineTranQuantity();
    }

    /**
     * Create an instance of {@link OrderLineOptions }
     * 
     */
    public OrderLineOptions createOrderLineOptions() {
        return new OrderLineOptions();
    }

    /**
     * Create an instance of {@link OrderLineOption.CustomAttributes }
     * 
     */
    public OrderLineOption.CustomAttributes createOrderLineOptionCustomAttributes() {
        return new OrderLineOption.CustomAttributes();
    }

    /**
     * Create an instance of {@link Opportunity.CustomAttributes }
     * 
     */
    public Opportunity.CustomAttributes createOpportunityCustomAttributes() {
        return new Opportunity.CustomAttributes();
    }

    /**
     * Create an instance of {@link LinePriceInfo }
     * 
     */
    public LinePriceInfo createLinePriceInfo() {
        return new LinePriceInfo();
    }

    /**
     * Create an instance of {@link OrderOverride }
     * 
     */
    public OrderOverride createOrderOverride() {
        return new OrderOverride();
    }

    /**
     * Create an instance of {@link OrderTag }
     * 
     */
    public OrderTag createOrderTag() {
        return new OrderTag();
    }

    /**
     * Create an instance of {@link PersonInfoContact }
     * 
     */
    public PersonInfoContact createPersonInfoContact() {
        return new PersonInfoContact();
    }

    /**
     * Create an instance of {@link OrderLineReservations }
     * 
     */
    public OrderLineReservations createOrderLineReservations() {
        return new OrderLineReservations();
    }

    /**
     * Create an instance of {@link DerivedFrom }
     * 
     */
    public DerivedFrom createDerivedFrom() {
        return new DerivedFrom();
    }

    /**
     * Create an instance of {@link PersonInfoSoldTo }
     * 
     */
    public PersonInfoSoldTo createPersonInfoSoldTo() {
        return new PersonInfoSoldTo();
    }

    /**
     * Create an instance of {@link OrderSearchConditions }
     * 
     */
    public OrderSearchConditions createOrderSearchConditions() {
        return new OrderSearchConditions();
    }

    /**
     * Create an instance of {@link OrderLineInvAttRequest }
     * 
     */
    public OrderLineInvAttRequest createOrderLineInvAttRequest() {
        return new OrderLineInvAttRequest();
    }

    /**
     * Create an instance of {@link OrderTags }
     * 
     */
    public OrderTags createOrderTags() {
        return new OrderTags();
    }

    /**
     * Create an instance of {@link Opportunity.Notes.Note }
     * 
     */
    public Opportunity.Notes.Note createOpportunityNotesNote() {
        return new Opportunity.Notes.Note();
    }

    /**
     * Create an instance of {@link CustomAuditDetails.OrderAuditDetail.Attributes.Attribute }
     * 
     */
    public CustomAuditDetails.OrderAuditDetail.Attributes.Attribute createCustomAuditDetailsOrderAuditDetailAttributesAttribute() {
        return new CustomAuditDetails.OrderAuditDetail.Attributes.Attribute();
    }

    /**
     * Create an instance of {@link CustomAuditDetails.OrderAuditDetail.IDs.ID }
     * 
     */
    public CustomAuditDetails.OrderAuditDetail.IDs.ID createCustomAuditDetailsOrderAuditDetailIDsID() {
        return new CustomAuditDetails.OrderAuditDetail.IDs.ID();
    }

    /**
     * Create an instance of {@link OrderLines.OrderLine.PersonInfoShipTo }
     * 
     */
    public OrderLines.OrderLine.PersonInfoShipTo createOrderLinesOrderLinePersonInfoShipTo() {
        return new OrderLines.OrderLine.PersonInfoShipTo();
    }

    /**
     * Create an instance of {@link OrderLines.OrderLine.PersonInfoMarkFor }
     * 
     */
    public OrderLines.OrderLine.PersonInfoMarkFor createOrderLinesOrderLinePersonInfoMarkFor() {
        return new OrderLines.OrderLine.PersonInfoMarkFor();
    }

    /**
     * Create an instance of {@link OrderLines.OrderLine.CustomAttributes }
     * 
     */
    public OrderLines.OrderLine.CustomAttributes createOrderLinesOrderLineCustomAttributes() {
        return new OrderLines.OrderLine.CustomAttributes();
    }

    /**
     * Create an instance of {@link OrderLines.OrderLine.OrderHoldTypes.OrderHoldType }
     * 
     */
    public OrderLines.OrderLine.OrderHoldTypes.OrderHoldType createOrderLinesOrderLineOrderHoldTypesOrderHoldType() {
        return new OrderLines.OrderLine.OrderHoldTypes.OrderHoldType();
    }

    /**
     * Create an instance of {@link OrderLines.OrderLine.Notes.Note }
     * 
     */
    public OrderLines.OrderLine.Notes.Note createOrderLinesOrderLineNotesNote() {
        return new OrderLines.OrderLine.Notes.Note();
    }

    /**
     * Create an instance of {@link OrderLines.OrderLine.Awards.Award.PromotionReferences.PromotionReference }
     * 
     */
    public OrderLines.OrderLine.Awards.Award.PromotionReferences.PromotionReference createOrderLinesOrderLineAwardsAwardPromotionReferencesPromotionReference() {
        return new OrderLines.OrderLine.Awards.Award.PromotionReferences.PromotionReference();
    }

    /**
     * Create an instance of {@link OrderLines.OrderLine.Promotions.Promotion }
     * 
     */
    public OrderLines.OrderLine.Promotions.Promotion createOrderLinesOrderLinePromotionsPromotion() {
        return new OrderLines.OrderLine.Promotions.Promotion();
    }

    /**
     * Create an instance of {@link OrderLines.OrderLine.OrderDates.OrderDate }
     * 
     */
    public OrderLines.OrderLine.OrderDates.OrderDate createOrderLinesOrderLineOrderDatesOrderDate() {
        return new OrderLines.OrderLine.OrderDates.OrderDate();
    }

    /**
     * Create an instance of {@link OrderLines.OrderLine.AdditionalAddresses.AdditionalAddress.PersonInfo }
     * 
     */
    public OrderLines.OrderLine.AdditionalAddresses.AdditionalAddress.PersonInfo createOrderLinesOrderLineAdditionalAddressesAdditionalAddressPersonInfo() {
        return new OrderLines.OrderLine.AdditionalAddresses.AdditionalAddress.PersonInfo();
    }

    /**
     * Create an instance of {@link OrderLines.OrderLine.References.Reference }
     * 
     */
    public OrderLines.OrderLine.References.Reference createOrderLinesOrderLineReferencesReference() {
        return new OrderLines.OrderLine.References.Reference();
    }

    /**
     * Create an instance of {@link OrderLines.OrderLine.Instructions.Instruction }
     * 
     */
    public OrderLines.OrderLine.Instructions.Instruction createOrderLinesOrderLineInstructionsInstruction() {
        return new OrderLines.OrderLine.Instructions.Instruction();
    }

    /**
     * Create an instance of {@link FulfillmentOrderBean.PersonInfoShipTo }
     * 
     */
    public FulfillmentOrderBean.PersonInfoShipTo createOrderXSDTypePersonInfoShipTo() {
        return new FulfillmentOrderBean.PersonInfoShipTo();
    }

    /**
     * Create an instance of {@link FulfillmentOrderBean.PersonInfoBillTo }
     * 
     */
    public FulfillmentOrderBean.PersonInfoBillTo createOrderXSDTypePersonInfoBillTo() {
        return new FulfillmentOrderBean.PersonInfoBillTo();
    }

    /**
     * Create an instance of {@link FulfillmentOrderBean.PersonInfoMarkFor }
     * 
     */
    public FulfillmentOrderBean.PersonInfoMarkFor createOrderXSDTypePersonInfoMarkFor() {
        return new FulfillmentOrderBean.PersonInfoMarkFor();
    }

    /**
     * Create an instance of {@link FulfillmentOrderBean.CustomAttributes }
     * 
     */
    public FulfillmentOrderBean.CustomAttributes createOrderXSDTypeCustomAttributes() {
        return new FulfillmentOrderBean.CustomAttributes();
    }

    /**
     * Create an instance of {@link FulfillmentOrderBean.Awards.Award }
     * 
     */
    public FulfillmentOrderBean.Awards.Award createOrderXSDTypeAwardsAward() {
        return new FulfillmentOrderBean.Awards.Award();
    }

    /**
     * Create an instance of {@link FulfillmentOrderBean.Promotions.Promotion.PromotionReferences.PromotionReference }
     * 
     */
    public FulfillmentOrderBean.Promotions.Promotion.PromotionReferences.PromotionReference createOrderXSDTypePromotionsPromotionPromotionReferencesPromotionReference() {
        return new FulfillmentOrderBean.Promotions.Promotion.PromotionReferences.PromotionReference();
    }

    /**
     * Create an instance of {@link FulfillmentOrderBean.OrderHoldTypes.OrderHoldType }
     * 
     */
    public FulfillmentOrderBean.OrderHoldTypes.OrderHoldType createOrderXSDTypeOrderHoldTypesOrderHoldType() {
        return new FulfillmentOrderBean.OrderHoldTypes.OrderHoldType();
    }

    /**
     * Create an instance of {@link FulfillmentOrderBean.OrderDates.OrderDate }
     * 
     */
    public FulfillmentOrderBean.OrderDates.OrderDate createOrderXSDTypeOrderDatesOrderDate() {
        return new FulfillmentOrderBean.OrderDates.OrderDate();
    }

    /**
     * Create an instance of {@link FulfillmentOrderBean.References.Reference }
     * 
     */
    public FulfillmentOrderBean.References.Reference createOrderXSDTypeReferencesReference() {
        return new FulfillmentOrderBean.References.Reference();
    }

    /**
     * Create an instance of {@link FulfillmentOrderBean.AdditionalAddresses.AdditionalAddress.PersonInfo }
     * 
     */
    public FulfillmentOrderBean.AdditionalAddresses.AdditionalAddress.PersonInfo createOrderXSDTypeAdditionalAddressesAdditionalAddressPersonInfo() {
        return new FulfillmentOrderBean.AdditionalAddresses.AdditionalAddress.PersonInfo();
    }

    /**
     * Create an instance of {@link FulfillmentOrderBean.Instructions.Instruction }
     * 
     */
    public FulfillmentOrderBean.Instructions.Instruction createOrderXSDTypeInstructionsInstruction() {
        return new FulfillmentOrderBean.Instructions.Instruction();
    }

    /**
     * Create an instance of {@link FulfillmentOrderBean.Notes.Note }
     * 
     */
    public FulfillmentOrderBean.Notes.Note createOrderXSDTypeNotesNote() {
        return new FulfillmentOrderBean.Notes.Note();
    }

    /**
     * Create an instance of {@link OrderAuditDetails.OrderAuditDetail.Attributes.Attribute }
     * 
     */
    public OrderAuditDetails.OrderAuditDetail.Attributes.Attribute createOrderAuditDetailsOrderAuditDetailAttributesAttribute() {
        return new OrderAuditDetails.OrderAuditDetail.Attributes.Attribute();
    }

    /**
     * Create an instance of {@link OrderAuditDetails.OrderAuditDetail.IDs.ID }
     * 
     */
    public OrderAuditDetails.OrderAuditDetail.IDs.ID createOrderAuditDetailsOrderAuditDetailIDsID() {
        return new OrderAuditDetails.OrderAuditDetail.IDs.ID();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FulfillmentOrderBean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.sterlingcommerce.com/documentation/YFS/createOrder/input", name = "Order")
    public JAXBElement<FulfillmentOrderBean> createOrder(FulfillmentOrderBean value) {
        return new JAXBElement<FulfillmentOrderBean>(_Order_QNAME, FulfillmentOrderBean.class, null, value);
    }

}
