//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.25 at 03:34:08 AM GMT 
//


package com.tesco.ofs.order.representation;

import java.math.BigDecimal;
import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import com.fasterxml.jackson.annotation.JsonProperty;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="FillQuantity" type="{http://www.sterlingcommerce.com/documentation/types}Quantity" />
 *       &lt;attribute name="KitQty" type="{http://www.sterlingcommerce.com/documentation/types}LineNo" />
 *       &lt;attribute name="OrderedQty" type="{http://www.sterlingcommerce.com/documentation/types}Quantity" />
 *       &lt;attribute name="TransactionalUOM" type="{http://www.sterlingcommerce.com/documentation/types}UOM" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "OrderLineTranQuantity")
public class OrderLineTranQuantity {

    @XmlAttribute(name = "FillQuantity")
    protected BigDecimal fillQuantity;
    @XmlAttribute(name = "KitQty")
    protected BigInteger kitQty;
    @XmlAttribute(name = "OrderedQty")
    @JsonProperty("UnitOfSale")
    protected BigDecimal orderedQty;
    @XmlAttribute(name = "TransactionalUOM")
    protected String transactionalUOM;

    /**
     * Gets the value of the fillQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFillQuantity() {
        return fillQuantity;
    }

    /**
     * Sets the value of the fillQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFillQuantity(BigDecimal value) {
        this.fillQuantity = value;
    }

    /**
     * Gets the value of the kitQty property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getKitQty() {
        return kitQty;
    }

    /**
     * Sets the value of the kitQty property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setKitQty(BigInteger value) {
        this.kitQty = value;
    }

    /**
     * Gets the value of the orderedQty property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getOrderedQty() {
        return orderedQty;
    }

    /**
     * Sets the value of the orderedQty property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setOrderedQty(BigDecimal value) {
        this.orderedQty = value;
    }

    /**
     * Gets the value of the transactionalUOM property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionalUOM() {
        return transactionalUOM;
    }

    /**
     * Sets the value of the transactionalUOM property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionalUOM(String value) {
        this.transactionalUOM = value;
    }

}
