//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.25 at 03:34:08 AM GMT 
//


package com.tesco.ofs.order.representation;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="DocumentType" type="{http://www.sterlingcommerce.com/documentation/types}Text-40" />
 *       &lt;attribute name="EnterpriseCode" type="{http://www.sterlingcommerce.com/documentation/types}OrgCode" />
 *       &lt;attribute name="EntityAttributeName" type="{http://www.sterlingcommerce.com/documentation/types}Text-400" />
 *       &lt;attribute name="EntityAttributeValue" type="{http://www.sterlingcommerce.com/documentation/types}Text-400" />
 *       &lt;attribute name="Operation">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.sterlingcommerce.com/documentation/types}String">
 *             &lt;enumeration value="Manage"/>
 *             &lt;enumeration value="Delete"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="OrderNo" type="{http://www.sterlingcommerce.com/documentation/types}VarcharDocumentNo" />
 *       &lt;attribute name="OrderSearchConditionKey" type="{http://www.sterlingcommerce.com/documentation/types}Key" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "OrderSearchCondition")
public class OrderSearchCondition {

    @XmlAttribute(name = "DocumentType")
    protected String documentType;
    @XmlAttribute(name = "EnterpriseCode")
    protected String enterpriseCode;
    @XmlAttribute(name = "EntityAttributeName")
    protected String entityAttributeName;
    @XmlAttribute(name = "EntityAttributeValue")
    protected String entityAttributeValue;
    @XmlAttribute(name = "Operation")
    protected String operation;
    @XmlAttribute(name = "OrderNo")
    protected String orderNo;
    @XmlAttribute(name = "OrderSearchConditionKey")
    protected String orderSearchConditionKey;

    /**
     * Gets the value of the documentType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentType() {
        return documentType;
    }

    /**
     * Sets the value of the documentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentType(String value) {
        this.documentType = value;
    }

    /**
     * Gets the value of the enterpriseCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnterpriseCode() {
        return enterpriseCode;
    }

    /**
     * Sets the value of the enterpriseCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnterpriseCode(String value) {
        this.enterpriseCode = value;
    }

    /**
     * Gets the value of the entityAttributeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntityAttributeName() {
        return entityAttributeName;
    }

    /**
     * Sets the value of the entityAttributeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntityAttributeName(String value) {
        this.entityAttributeName = value;
    }

    /**
     * Gets the value of the entityAttributeValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntityAttributeValue() {
        return entityAttributeValue;
    }

    /**
     * Sets the value of the entityAttributeValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntityAttributeValue(String value) {
        this.entityAttributeValue = value;
    }

    /**
     * Gets the value of the operation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperation() {
        return operation;
    }

    /**
     * Sets the value of the operation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperation(String value) {
        this.operation = value;
    }

    /**
     * Gets the value of the orderNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * Sets the value of the orderNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderNo(String value) {
        this.orderNo = value;
    }

    /**
     * Gets the value of the orderSearchConditionKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderSearchConditionKey() {
        return orderSearchConditionKey;
    }

    /**
     * Sets the value of the orderSearchConditionKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderSearchConditionKey(String value) {
        this.orderSearchConditionKey = value;
    }

}
