//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.25 at 03:34:08 AM GMT 
//


package com.tesco.ofs.order.representation;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="InventoryCheckCode" type="{http://www.sterlingcommerce.com/documentation/types}EnumInvCheckCode" />
 *       &lt;attribute name="Node" type="{http://www.sterlingcommerce.com/documentation/types}Key" />
 *       &lt;attribute name="ReasonText" type="{http://www.sterlingcommerce.com/documentation/types}ReasonText" />
 *       &lt;attribute name="SuppressNodeCapacity">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.sterlingcommerce.com/documentation/types}Flag">
 *             &lt;enumeration value="N"/>
 *             &lt;enumeration value="Y"/>
 *             &lt;enumeration value=""/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="SuppressProcurement">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.sterlingcommerce.com/documentation/types}Flag">
 *             &lt;enumeration value="Y"/>
 *             &lt;enumeration value="N"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="SuppressSourcing">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.sterlingcommerce.com/documentation/types}Flag">
 *             &lt;enumeration value="Y"/>
 *             &lt;enumeration value="N"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "OrderLineSourcingCntrl")
public class OrderLineSourcingCntrl {

    @XmlAttribute(name = "InventoryCheckCode")
    protected String inventoryCheckCode;
    @XmlAttribute(name = "Node")
    protected String node;
    @XmlAttribute(name = "ReasonText")
    protected String reasonText;
    @XmlAttribute(name = "SuppressNodeCapacity")
    protected String suppressNodeCapacity;
    @XmlAttribute(name = "SuppressProcurement")
    protected String suppressProcurement;
    @XmlAttribute(name = "SuppressSourcing")
    protected String suppressSourcing;

    /**
     * Gets the value of the inventoryCheckCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInventoryCheckCode() {
        return inventoryCheckCode;
    }

    /**
     * Sets the value of the inventoryCheckCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInventoryCheckCode(String value) {
        this.inventoryCheckCode = value;
    }

    /**
     * Gets the value of the node property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNode() {
        return node;
    }

    /**
     * Sets the value of the node property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNode(String value) {
        this.node = value;
    }

    /**
     * Gets the value of the reasonText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReasonText() {
        return reasonText;
    }

    /**
     * Sets the value of the reasonText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReasonText(String value) {
        this.reasonText = value;
    }

    /**
     * Gets the value of the suppressNodeCapacity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSuppressNodeCapacity() {
        return suppressNodeCapacity;
    }

    /**
     * Sets the value of the suppressNodeCapacity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSuppressNodeCapacity(String value) {
        this.suppressNodeCapacity = value;
    }

    /**
     * Gets the value of the suppressProcurement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSuppressProcurement() {
        return suppressProcurement;
    }

    /**
     * Sets the value of the suppressProcurement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSuppressProcurement(String value) {
        this.suppressProcurement = value;
    }

    /**
     * Gets the value of the suppressSourcing property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSuppressSourcing() {
        return suppressSourcing;
    }

    /**
     * Sets the value of the suppressSourcing property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSuppressSourcing(String value) {
        this.suppressSourcing = value;
    }

}
