//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.25 at 03:34:08 AM GMT 
//


package com.tesco.ofs.order.representation;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import com.fasterxml.jackson.annotation.JsonIgnore;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{http://www.sterlingcommerce.com/documentation/YFS/createOrder/input}OrderAuditLevels" minOccurs="0"/>
 *       &lt;/all>
 *       &lt;attribute name="AuditTransactionId" type="{http://www.sterlingcommerce.com/documentation/types}TransactionID" />
 *       &lt;attribute name="Createts" type="{http://www.sterlingcommerce.com/documentation/types}TimeStamp" />
 *       &lt;attribute name="Createuserid" type="{http://www.sterlingcommerce.com/documentation/types}Createuserid" />
 *       &lt;attribute name="Modifyuserid" type="{http://www.sterlingcommerce.com/documentation/types}Modifyuserid" />
 *       &lt;attribute name="NewBuffer" type="{http://www.sterlingcommerce.com/documentation/types}Text-1500" />
 *       &lt;attribute name="OldBuffer" type="{http://www.sterlingcommerce.com/documentation/types}Text-1500" />
 *       &lt;attribute name="OrderHeaderKey" type="{http://www.sterlingcommerce.com/documentation/types}Key" />
 *       &lt;attribute name="ReasonCode" type="{http://www.sterlingcommerce.com/documentation/types}ReasonCode" />
 *       &lt;attribute name="ReasonText" type="{http://www.sterlingcommerce.com/documentation/types}ReasonText" />
 *       &lt;attribute name="Reference1" type="{http://www.sterlingcommerce.com/documentation/types}Text-254" />
 *       &lt;attribute name="Reference2" type="{http://www.sterlingcommerce.com/documentation/types}Text-254" />
 *       &lt;attribute name="Reference3" type="{http://www.sterlingcommerce.com/documentation/types}Text-254" />
 *       &lt;attribute name="Reference4" type="{http://www.sterlingcommerce.com/documentation/types}Text-254" />
 *       &lt;attribute name="XMLFlag" type="{http://www.sterlingcommerce.com/documentation/types}Flag" />
 *       &lt;attribute name="isHistory" type="{http://www.sterlingcommerce.com/documentation/types}String" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "OrderAudit")
public class OrderAudit {

    @XmlElement(name = "OrderAuditLevels")
    protected OrderAuditLevels orderAuditLevels;
    @XmlAttribute(name = "AuditTransactionId")
    protected String auditTransactionId;
    @XmlAttribute(name = "Createts")
    @JsonIgnore
    protected String createts;
    @XmlAttribute(name = "Createuserid")
    protected String createuserid;
    @XmlAttribute(name = "Modifyuserid")
    protected String modifyuserid;
    @XmlAttribute(name = "NewBuffer")
    protected String newBuffer;
    @XmlAttribute(name = "OldBuffer")
    protected String oldBuffer;
    @XmlAttribute(name = "OrderHeaderKey")
    protected String orderHeaderKey;
    @XmlAttribute(name = "ReasonCode")
    protected String reasonCode;
    @XmlAttribute(name = "ReasonText")
    protected String reasonText;
    @XmlAttribute(name = "Reference1")
    protected String reference1;
    @XmlAttribute(name = "Reference2")
    protected String reference2;
    @XmlAttribute(name = "Reference3")
    protected String reference3;
    @XmlAttribute(name = "Reference4")
    protected String reference4;
    @XmlAttribute(name = "XMLFlag")
    protected String xmlFlag;
    @XmlAttribute(name = "isHistory")
    protected String isHistory;

    /**
     * Gets the value of the orderAuditLevels property.
     * 
     * @return
     *     possible object is
     *     {@link OrderAuditLevels }
     *     
     */
    public OrderAuditLevels getOrderAuditLevels() {
        return orderAuditLevels;
    }

    /**
     * Sets the value of the orderAuditLevels property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderAuditLevels }
     *     
     */
    public void setOrderAuditLevels(OrderAuditLevels value) {
        this.orderAuditLevels = value;
    }

    /**
     * Gets the value of the auditTransactionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuditTransactionId() {
        return auditTransactionId;
    }

    /**
     * Sets the value of the auditTransactionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuditTransactionId(String value) {
        this.auditTransactionId = value;
    }

    /**
     * Gets the value of the createts property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreatets() {
        return createts;
    }

    /**
     * Sets the value of the createts property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreatets(String value) {
        this.createts = value;
    }

    /**
     * Gets the value of the createuserid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreateuserid() {
        return createuserid;
    }

    /**
     * Sets the value of the createuserid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreateuserid(String value) {
        this.createuserid = value;
    }

    /**
     * Gets the value of the modifyuserid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModifyuserid() {
        return modifyuserid;
    }

    /**
     * Sets the value of the modifyuserid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModifyuserid(String value) {
        this.modifyuserid = value;
    }

    /**
     * Gets the value of the newBuffer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNewBuffer() {
        return newBuffer;
    }

    /**
     * Sets the value of the newBuffer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNewBuffer(String value) {
        this.newBuffer = value;
    }

    /**
     * Gets the value of the oldBuffer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOldBuffer() {
        return oldBuffer;
    }

    /**
     * Sets the value of the oldBuffer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOldBuffer(String value) {
        this.oldBuffer = value;
    }

    /**
     * Gets the value of the orderHeaderKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderHeaderKey() {
        return orderHeaderKey;
    }

    /**
     * Sets the value of the orderHeaderKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderHeaderKey(String value) {
        this.orderHeaderKey = value;
    }

    /**
     * Gets the value of the reasonCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReasonCode() {
        return reasonCode;
    }

    /**
     * Sets the value of the reasonCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReasonCode(String value) {
        this.reasonCode = value;
    }

    /**
     * Gets the value of the reasonText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReasonText() {
        return reasonText;
    }

    /**
     * Sets the value of the reasonText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReasonText(String value) {
        this.reasonText = value;
    }

    /**
     * Gets the value of the reference1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReference1() {
        return reference1;
    }

    /**
     * Sets the value of the reference1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReference1(String value) {
        this.reference1 = value;
    }

    /**
     * Gets the value of the reference2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReference2() {
        return reference2;
    }

    /**
     * Sets the value of the reference2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReference2(String value) {
        this.reference2 = value;
    }

    /**
     * Gets the value of the reference3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReference3() {
        return reference3;
    }

    /**
     * Sets the value of the reference3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReference3(String value) {
        this.reference3 = value;
    }

    /**
     * Gets the value of the reference4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReference4() {
        return reference4;
    }

    /**
     * Sets the value of the reference4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReference4(String value) {
        this.reference4 = value;
    }

    /**
     * Gets the value of the xmlFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXMLFlag() {
        return xmlFlag;
    }

    /**
     * Sets the value of the xmlFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXMLFlag(String value) {
        this.xmlFlag = value;
    }

    /**
     * Gets the value of the isHistory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsHistory() {
        return isHistory;
    }

    /**
     * Sets the value of the isHistory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsHistory(String value) {
        this.isHistory = value;
    }

}
