//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.25 at 03:34:08 AM GMT 
//


package com.tesco.ofs.order.representation;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="QuantityLimitOverridden" type="{http://www.sterlingcommerce.com/documentation/types}Flag" />
 *       &lt;attribute name="ValidateItem" type="{http://www.sterlingcommerce.com/documentation/types}Flag" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "OrderOverride")
public class OrderOverride {

    @XmlAttribute(name = "QuantityLimitOverridden")
    protected String quantityLimitOverridden;
    @XmlAttribute(name = "ValidateItem")
    protected String validateItem;

    /**
     * Gets the value of the quantityLimitOverridden property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQuantityLimitOverridden() {
        return quantityLimitOverridden;
    }

    /**
     * Sets the value of the quantityLimitOverridden property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuantityLimitOverridden(String value) {
        this.quantityLimitOverridden = value;
    }

    /**
     * Gets the value of the validateItem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValidateItem() {
        return validateItem;
    }

    /**
     * Sets the value of the validateItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValidateItem(String value) {
        this.validateItem = value;
    }

}
