//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.25 at 03:34:08 AM GMT 
//


package com.tesco.ofs.order.representation;

import java.math.BigDecimal;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import com.fasterxml.jackson.annotation.JsonIgnore;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="BatchNo" type="{http://www.sterlingcommerce.com/documentation/types}Text-40" />
 *       &lt;attribute name="DemandType" type="{http://www.sterlingcommerce.com/documentation/types}Text-40" />
 *       &lt;attribute name="ItemID" use="required" type="{http://www.sterlingcommerce.com/documentation/types}ItemID" />
 *       &lt;attribute name="LotNumber" type="{http://www.sterlingcommerce.com/documentation/types}Text-40" />
 *       &lt;attribute name="Node" use="required" type="{http://www.sterlingcommerce.com/documentation/types}Key" />
 *       &lt;attribute name="ProductClass" type="{http://www.sterlingcommerce.com/documentation/types}ProductClass" />
 *       &lt;attribute name="Quantity" use="required" type="{http://www.sterlingcommerce.com/documentation/types}Quantity" />
 *       &lt;attribute name="RequestedReservationDate" type="{http://www.sterlingcommerce.com/documentation/types}TimeStamp" />
 *       &lt;attribute name="ReservationID" type="{http://www.sterlingcommerce.com/documentation/types}Text-100" />
 *       &lt;attribute name="RevisionNo" type="{http://www.sterlingcommerce.com/documentation/types}Text-40" />
 *       &lt;attribute name="UnitOfMeasure" type="{http://www.sterlingcommerce.com/documentation/types}UOM" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "OrderLineReservation")
public class OrderLineReservation {

    @XmlAttribute(name = "BatchNo")
    protected String batchNo;
    @XmlAttribute(name = "DemandType")
    protected String demandType;
    @XmlAttribute(name = "ItemID", required = true)
    protected String itemID;
    @XmlAttribute(name = "LotNumber")
    protected String lotNumber;
    @XmlAttribute(name = "Node", required = true)
    protected String node;
    @XmlAttribute(name = "ProductClass")
    protected String productClass;
    @XmlAttribute(name = "Quantity", required = true)
    protected BigDecimal quantity;
    @XmlAttribute(name = "RequestedReservationDate")
    @JsonIgnore
    protected String requestedReservationDate;
    @XmlAttribute(name = "ReservationID")
    protected String reservationID;
    @XmlAttribute(name = "RevisionNo")
    protected String revisionNo;
    @XmlAttribute(name = "UnitOfMeasure")
    protected String unitOfMeasure;

    /**
     * Gets the value of the batchNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBatchNo() {
        return batchNo;
    }

    /**
     * Sets the value of the batchNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBatchNo(String value) {
        this.batchNo = value;
    }

    /**
     * Gets the value of the demandType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDemandType() {
        return demandType;
    }

    /**
     * Sets the value of the demandType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDemandType(String value) {
        this.demandType = value;
    }

    /**
     * Gets the value of the itemID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemID() {
        return itemID;
    }

    /**
     * Sets the value of the itemID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemID(String value) {
        this.itemID = value;
    }

    /**
     * Gets the value of the lotNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLotNumber() {
        return lotNumber;
    }

    /**
     * Sets the value of the lotNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLotNumber(String value) {
        this.lotNumber = value;
    }

    /**
     * Gets the value of the node property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNode() {
        return node;
    }

    /**
     * Sets the value of the node property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNode(String value) {
        this.node = value;
    }

    /**
     * Gets the value of the productClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductClass() {
        return productClass;
    }

    /**
     * Sets the value of the productClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductClass(String value) {
        this.productClass = value;
    }

    /**
     * Gets the value of the quantity property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getQuantity() {
        return quantity;
    }

    /**
     * Sets the value of the quantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setQuantity(BigDecimal value) {
        this.quantity = value;
    }

    /**
     * Gets the value of the requestedReservationDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestedReservationDate() {
        return requestedReservationDate;
    }

    /**
     * Sets the value of the requestedReservationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestedReservationDate(String value) {
        this.requestedReservationDate = value;
    }

    /**
     * Gets the value of the reservationID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReservationID() {
        return reservationID;
    }

    /**
     * Sets the value of the reservationID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReservationID(String value) {
        this.reservationID = value;
    }

    /**
     * Gets the value of the revisionNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRevisionNo() {
        return revisionNo;
    }

    /**
     * Sets the value of the revisionNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRevisionNo(String value) {
        this.revisionNo = value;
    }

    /**
     * Gets the value of the unitOfMeasure property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnitOfMeasure() {
        return unitOfMeasure;
    }

    /**
     * Sets the value of the unitOfMeasure property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnitOfMeasure(String value) {
        this.unitOfMeasure = value;
    }

}
