//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.25 at 03:34:08 AM GMT 
//


package com.tesco.ofs.order.representation;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="OrderLine" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="PrimeLineNo" type="{http://www.sterlingcommerce.com/documentation/types}LineNo" />
 *                 &lt;attribute name="SubLineNo" type="{http://www.sterlingcommerce.com/documentation/types}LineNo" />
 *                 &lt;attribute name="TransactionalLineId" type="{http://www.sterlingcommerce.com/documentation/types}Text-40" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{http://www.sterlingcommerce.com/documentation/YFS/createOrder/input}OrderAuditDetails" minOccurs="0"/>
 *         &lt;element ref="{http://www.sterlingcommerce.com/documentation/YFS/createOrder/input}ModificationTypes" minOccurs="0"/>
 *       &lt;/all>
 *       &lt;attribute name="ModificationLevel" type="{http://www.sterlingcommerce.com/documentation/types}Text-40" />
 *       &lt;attribute name="ModificationType" type="{http://www.sterlingcommerce.com/documentation/types}Text-4000" />
 *       &lt;attribute name="OrderLineKey" type="{http://www.sterlingcommerce.com/documentation/types}Key" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "OrderAuditLevel")
public class OrderAuditLevel {

    @XmlElement(name = "OrderLine")
    protected OrderAuditLevel.OrderLine orderLine;
    @XmlElement(name = "OrderAuditDetails")
    protected OrderAuditDetails orderAuditDetails;
    @XmlElement(name = "ModificationTypes")
    protected ModificationTypes modificationTypes;
    @XmlAttribute(name = "ModificationLevel")
    protected String modificationLevel;
    @XmlAttribute(name = "ModificationType")
    protected String modificationType;
    @XmlAttribute(name = "OrderLineKey")
    protected String orderLineKey;

    /**
     * Gets the value of the orderLine property.
     * 
     * @return
     *     possible object is
     *     {@link OrderAuditLevel.OrderLine }
     *     
     */
    public OrderAuditLevel.OrderLine getOrderLine() {
        return orderLine;
    }

    /**
     * Sets the value of the orderLine property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderAuditLevel.OrderLine }
     *     
     */
    public void setOrderLine(OrderAuditLevel.OrderLine value) {
        this.orderLine = value;
    }

    /**
     * Gets the value of the orderAuditDetails property.
     * 
     * @return
     *     possible object is
     *     {@link OrderAuditDetails }
     *     
     */
    public OrderAuditDetails getOrderAuditDetails() {
        return orderAuditDetails;
    }

    /**
     * Sets the value of the orderAuditDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderAuditDetails }
     *     
     */
    public void setOrderAuditDetails(OrderAuditDetails value) {
        this.orderAuditDetails = value;
    }

    /**
     * Gets the value of the modificationTypes property.
     * 
     * @return
     *     possible object is
     *     {@link ModificationTypes }
     *     
     */
    public ModificationTypes getModificationTypes() {
        return modificationTypes;
    }

    /**
     * Sets the value of the modificationTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link ModificationTypes }
     *     
     */
    public void setModificationTypes(ModificationTypes value) {
        this.modificationTypes = value;
    }

    /**
     * Gets the value of the modificationLevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModificationLevel() {
        return modificationLevel;
    }

    /**
     * Sets the value of the modificationLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModificationLevel(String value) {
        this.modificationLevel = value;
    }

    /**
     * Gets the value of the modificationType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModificationType() {
        return modificationType;
    }

    /**
     * Sets the value of the modificationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModificationType(String value) {
        this.modificationType = value;
    }

    /**
     * Gets the value of the orderLineKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderLineKey() {
        return orderLineKey;
    }

    /**
     * Sets the value of the orderLineKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderLineKey(String value) {
        this.orderLineKey = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="PrimeLineNo" type="{http://www.sterlingcommerce.com/documentation/types}LineNo" />
     *       &lt;attribute name="SubLineNo" type="{http://www.sterlingcommerce.com/documentation/types}LineNo" />
     *       &lt;attribute name="TransactionalLineId" type="{http://www.sterlingcommerce.com/documentation/types}Text-40" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class OrderLine {

        @XmlAttribute(name = "PrimeLineNo")
        protected BigInteger primeLineNo;
        @XmlAttribute(name = "SubLineNo")
        protected BigInteger subLineNo;
        @XmlAttribute(name = "TransactionalLineId")
        protected String transactionalLineId;

        /**
         * Gets the value of the primeLineNo property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getPrimeLineNo() {
            return primeLineNo;
        }

        /**
         * Sets the value of the primeLineNo property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setPrimeLineNo(BigInteger value) {
            this.primeLineNo = value;
        }

        /**
         * Gets the value of the subLineNo property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getSubLineNo() {
            return subLineNo;
        }

        /**
         * Sets the value of the subLineNo property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setSubLineNo(BigInteger value) {
            this.subLineNo = value;
        }

        /**
         * Gets the value of the transactionalLineId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTransactionalLineId() {
            return transactionalLineId;
        }

        /**
         * Sets the value of the transactionalLineId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTransactionalLineId(String value) {
            this.transactionalLineId = value;
        }

    }

}
