//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.25 at 03:34:08 AM GMT 
//


package com.tesco.ofs.order.representation;

import java.math.BigDecimal;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import com.fasterxml.jackson.annotation.JsonIgnore;



/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="Currency" type="{http://www.sterlingcommerce.com/documentation/types}Currency" />
 *       &lt;attribute name="EnterpriseCurrency" type="{http://www.sterlingcommerce.com/documentation/types}Currency" />
 *       &lt;attribute name="ReportingConversionDate" type="{http://www.sterlingcommerce.com/documentation/types}TimeStamp" />
 *       &lt;attribute name="ReportingConversionRate" type="{http://www.sterlingcommerce.com/documentation/types}ConversionRate" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "PriceInfo")
public class PriceInfo {

    @XmlAttribute(name = "Currency")
    protected String currency;
    @XmlAttribute(name = "EnterpriseCurrency")
    protected String enterpriseCurrency;
    @XmlAttribute(name = "ReportingConversionDate")
    @JsonIgnore
    protected String reportingConversionDate;
    @XmlAttribute(name = "ReportingConversionRate")
    protected BigDecimal reportingConversionRate;

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrency(String value) {
        this.currency = value;
    }

    /**
     * Gets the value of the enterpriseCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnterpriseCurrency() {
        return enterpriseCurrency;
    }

    /**
     * Sets the value of the enterpriseCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnterpriseCurrency(String value) {
        this.enterpriseCurrency = value;
    }

    /**
     * Gets the value of the reportingConversionDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportingConversionDate() {
        return reportingConversionDate;
    }

    /**
     * Sets the value of the reportingConversionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportingConversionDate(String value) {
        this.reportingConversionDate = value;
    }

    /**
     * Gets the value of the reportingConversionRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getReportingConversionRate() {
        return reportingConversionRate;
    }

    /**
     * Sets the value of the reportingConversionRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setReportingConversionRate(BigDecimal value) {
        this.reportingConversionRate = value;
    }

}
