//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.25 at 03:34:08 AM GMT 
//


package com.tesco.ofs.order.representation;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{http://www.sterlingcommerce.com/documentation/YFS/createOrder/input}ScheduleTranQuantity" minOccurs="0"/>
 *       &lt;/all>
 *       &lt;attribute name="BatchNo" type="{http://www.sterlingcommerce.com/documentation/types}Text-40" />
 *       &lt;attribute name="ChangeInQuantity" use="required" type="{http://www.sterlingcommerce.com/documentation/types}PositiveQuantity" />
 *       &lt;attribute name="LotNumber" type="{http://www.sterlingcommerce.com/documentation/types}Text-40" />
 *       &lt;attribute name="RevisionNo" type="{http://www.sterlingcommerce.com/documentation/types}Text-40" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "Schedule")
public class Schedule {

    @XmlElement(name = "ScheduleTranQuantity")
    protected ScheduleTranQuantity scheduleTranQuantity;
    @XmlAttribute(name = "BatchNo")
    protected String batchNo;
    @XmlAttribute(name = "ChangeInQuantity", required = true)
    protected BigInteger changeInQuantity;
    @XmlAttribute(name = "LotNumber")
    protected String lotNumber;
    @XmlAttribute(name = "RevisionNo")
    protected String revisionNo;

    /**
     * Gets the value of the scheduleTranQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link ScheduleTranQuantity }
     *     
     */
    public ScheduleTranQuantity getScheduleTranQuantity() {
        return scheduleTranQuantity;
    }

    /**
     * Sets the value of the scheduleTranQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScheduleTranQuantity }
     *     
     */
    public void setScheduleTranQuantity(ScheduleTranQuantity value) {
        this.scheduleTranQuantity = value;
    }

    /**
     * Gets the value of the batchNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBatchNo() {
        return batchNo;
    }

    /**
     * Sets the value of the batchNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBatchNo(String value) {
        this.batchNo = value;
    }

    /**
     * Gets the value of the changeInQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getChangeInQuantity() {
        return changeInQuantity;
    }

    /**
     * Sets the value of the changeInQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setChangeInQuantity(BigInteger value) {
        this.changeInQuantity = value;
    }

    /**
     * Gets the value of the lotNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLotNumber() {
        return lotNumber;
    }

    /**
     * Sets the value of the lotNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLotNumber(String value) {
        this.lotNumber = value;
    }

    /**
     * Gets the value of the revisionNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRevisionNo() {
        return revisionNo;
    }

    /**
     * Sets the value of the revisionNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRevisionNo(String value) {
        this.revisionNo = value;
    }

}
